"""
Additional Comprehensive Medical Knowledge - Part 2
Adds more detailed entries for respiratory, renal, infectious, and other critical conditions.
"""

import json
from pathlib import Path

DATA_FILE = Path(__file__).parent / "disease-ontology" / "data" / "disease_ontology_compiled.jsonl"

def create_additional_medical_entries():
    """Create additional detailed medical entries."""
    
    entries = []
    
    # ==================== RESPIRATORY CONDITIONS ====================
    
    entries.append({
        "id": "MED:RESP:001",
        "name": "Community-Acquired Pneumonia",
        "description": "Community-acquired pneumonia (CAP) is an acute infection of the lung parenchyma acquired outside of hospital settings. Fourth leading cause of death worldwide. Most common cause of sepsis. Annual incidence 5-11 per 1000 adults. Mortality 1% outpatient, 5-15% hospitalized, 20-50% ICU.",
        "synonyms": ["CAP", "pneumonia", "lung infection", "bacterial pneumonia"],
        "related_synonyms": ["typical pneumonia", "atypical pneumonia", "lobar pneumonia", "bronchopneumonia"],
        "category": "respiratory/infectious disease",
        "pathophysiology": "Pathogens reach lower respiratory tract via aspiration of oropharyngeal flora, inhalation of aerosols, or hematogenous spread. Infection causes alveolar inflammation, exudate accumulation, impaired gas exchange.",
        "child_diseases": [],
        "common_pathogens": [
            "TYPICAL BACTERIA:",
            "Streptococcus pneumoniae (most common overall)",
            "Haemophilus influenzae",
            "Moraxella catarrhalis",
            "Staphylococcus aureus (including MRSA)",
            "Gram-negative rods (Klebsiella, Pseudomonas - risk factors)",
            "",
            "ATYPICAL PATHOGENS:",
            "Mycoplasma pneumoniae (young adults)",
            "Chlamydophila pneumoniae",
            "Legionella pneumophila (severe CAP)",
            "",
            "VIRAL:",
            "Influenza",
            "SARS-CoV-2 (COVID-19)",
            "RSV",
            "Parainfluenza"
        ],
        "symptoms": [
            "RESPIRATORY:",
            "cough (productive or dry)",
            "dyspnea",
            "pleuritic chest pain",
            "sputum production",
            "hemoptysis (rare)",
            "",
            "SYSTEMIC:",
            "fever and chills",
            "fatigue",
            "myalgias",
            "",
            "PHYSICAL EXAM:",
            "tachypnea",
            "tachycardia",
            "hypoxia",
            "crackles/rales on auscultation",
            "dullness to percussion",
            "bronchial breath sounds",
            "egophony",
            "",
            "ELDERLY MAY PRESENT ATYPICALLY:",
            "confusion without fever",
            "falls",
            "decompensation of chronic illness"
        ],
        "risk_factors": [
            "age >65 years",
            "smoking",
            "COPD or other chronic lung disease",
            "immunocompromised",
            "chronic diseases (diabetes, heart failure, kidney disease)",
            "alcoholism",
            "aspiration risk",
            "recent viral URI",
            "overcrowded living conditions"
        ],
        "severity_assessment": [
            "CURB-65 SCORE:",
            "Confusion: 1 point",
            "Urea >7 mmol/L (BUN >19): 1 point",
            "Respiratory rate ≥30: 1 point",
            "Blood pressure (SBP<90 or DBP≤60): 1 point",
            "Age ≥65: 1 point",
            "",
            "0-1: outpatient treatment",
            "2: consider hospitalization",
            "≥3: hospitalize, consider ICU if 4-5",
            "",
            "PSI/PORT SCORE: more comprehensive, 20+ variables"
        ],
        "diagnostics": [
            "chest X-ray (required for diagnosis)",
            "  - consolidation, infiltrates, air bronchograms",
            "pulse oximetry",
            "CBC, BMP (including BUN)",
            "procalcitonin (helps distinguish bacterial vs viral)",
            "",
            "HOSPITALIZED PATIENTS:",
            "blood cultures (before antibiotics)",
            "sputum culture and Gram stain",
            "Legionella and pneumococcal urinary antigens",
            "respiratory viral panel",
            "arterial blood gas if severe"
        ],
        "treatments": [
            "OUTPATIENT (healthy, no comorbidities):",
            "  - Amoxicillin 1g TID x 5 days",
            "  - OR Doxycycline 100mg BID x 5 days",
            "  - OR Azithromycin 500mg day 1, 250mg days 2-5 (if local resistance <25%)",
            "",
            "OUTPATIENT (comorbidities: COPD, diabetes, heart/liver/kidney disease):",
            "  - Amoxicillin-clavulanate 875mg BID + macrolide",
            "  - OR Respiratory fluoroquinolone (levofloxacin 750mg daily, moxifloxacin)",
            "",
            "INPATIENT (non-ICU):",
            "  - Beta-lactam (ceftriaxone 1g IV daily) + macrolide (azithromycin)",
            "  - OR Respiratory fluoroquinolone monotherapy",
            "",
            "INPATIENT (ICU):",
            "  - Beta-lactam (ceftriaxone, cefotaxime, or ampicillin-sulbactam) + macrolide",
            "  - OR Beta-lactam + respiratory fluoroquinolone",
            "  - If MRSA risk: add vancomycin or linezolid",
            "  - If Pseudomonas risk: piperacillin-tazobactam or cefepime",
            "",
            "DURATION: 5 days minimum, extend if not clinically stable",
            "",
            "SUPPORTIVE:",
            "supplemental oxygen (target SpO2 ≥94%)",
            "IV fluids if dehydrated",
            "antipyretics"
        ],
        "prevention": [
            "pneumococcal vaccination (PCV13, PPSV23, PCV20)",
            "influenza vaccination annually",
            "COVID-19 vaccination",
            "smoking cessation",
            "good oral hygiene"
        ],
        "source": "2019 ATS/IDSA Guidelines for CAP in Adults; 2023 IDSA Update",
        "citations": [
            "Metlay JP, et al. Diagnosis and Treatment of Adults with Community-acquired Pneumonia: An Official Clinical Practice Guideline of the ATS and IDSA. Am J Respir Crit Care Med. 2019;200:e45-e67",
            "Mandell LA, Niederman MS. Aspiration Pneumonia. N Engl J Med. 2019;380:651-663",
            "Wunderink RG, Waterer GW. Clinical practice. Community-acquired pneumonia. N Engl J Med. 2014;370:543-551"
        ],
        "text": "Disease: Community-Acquired Pneumonia | Description: Acute lung infection acquired outside hospital. Fourth leading cause of death worldwide. Most common sepsis cause. Mortality 1% outpatient to 50% ICU. | Symptoms: cough, dyspnea, pleuritic chest pain, fever, crackles on exam. Elderly may present with confusion only. | Common pathogens: S. pneumoniae, H. influenzae, Mycoplasma, Legionella, influenza | Diagnostics: CXR required, pulse ox, CBC, BMP. Hospitalized: blood/sputum cultures, urinary antigens. CURB-65 for severity | Treatments: Outpatient - amoxicillin or doxycycline. Inpatient - ceftriaxone+azithromycin or respiratory FQ. ICU - add MRSA/Pseudomonas coverage if risk. Duration 5+ days | Source: 2019 ATS/IDSA CAP Guidelines"
    })
    
    entries.append({
        "id": "MED:RESP:002",
        "name": "Acute Respiratory Distress Syndrome (ARDS)",
        "description": "ARDS is an acute, diffuse, inflammatory lung injury leading to increased pulmonary vascular permeability, hypoxemia, and bilateral radiographic opacities. Mortality 35-45%. Common in sepsis, pneumonia, aspiration, trauma. Requires mechanical ventilation with lung-protective strategies.",
        "synonyms": ["ARDS", "acute lung injury", "adult respiratory distress syndrome", "shock lung"],
        "related_synonyms": ["non-cardiogenic pulmonary edema", "acute hypoxemic respiratory failure"],
        "category": "pulmonary/critical care",
        "pathophysiology": "Inflammatory injury to alveolar-capillary membrane causes protein-rich edema fluid to flood alveoli. Surfactant dysfunction leads to atelectasis. Results in severe V/Q mismatch, shunt physiology, decreased lung compliance.",
        "child_diseases": [],
        "berlin_definition": [
            "TIMING: Within 1 week of clinical insult or new/worsening respiratory symptoms",
            "",
            "IMAGING: Bilateral opacities not fully explained by effusions, collapse, or nodules",
            "",
            "ORIGIN: Respiratory failure not fully explained by cardiac failure or fluid overload",
            "",
            "OXYGENATION (on PEEP ≥5 cm H2O):",
            "  Mild: PaO2/FiO2 200-300",
            "  Moderate: PaO2/FiO2 100-200",
            "  Severe: PaO2/FiO2 <100"
        ],
        "symptoms": [
            "rapid onset (hours to days)",
            "severe dyspnea",
            "tachypnea (RR often >30)",
            "hypoxemia refractory to supplemental oxygen",
            "labored breathing, accessory muscle use",
            "cyanosis",
            "diffuse crackles on auscultation"
        ],
        "common_causes": [
            "DIRECT LUNG INJURY:",
            "pneumonia (most common)",
            "aspiration of gastric contents",
            "inhalation injury",
            "pulmonary contusion",
            "near-drowning",
            "",
            "INDIRECT (SYSTEMIC):",
            "sepsis (most common indirect cause)",
            "severe trauma/multiple fractures",
            "pancreatitis",
            "massive transfusion",
            "drug overdose",
            "burns"
        ],
        "diagnostics": [
            "arterial blood gas (severe hypoxemia, calculate P/F ratio)",
            "chest X-ray (bilateral infiltrates)",
            "CT chest (diffuse ground-glass opacities, consolidation)",
            "echocardiogram (rule out cardiogenic pulmonary edema)",
            "BNP/NT-proBNP (to exclude cardiac cause)",
            "pulmonary artery catheter if diagnostic uncertainty (PCWP <18 mmHg)"
        ],
        "treatments": [
            "LUNG-PROTECTIVE MECHANICAL VENTILATION (ARDSNet protocol):",
            "  - Low tidal volume: 6 mL/kg predicted body weight (PBW)",
            "  - Plateau pressure ≤30 cm H2O",
            "  - Higher PEEP strategy (PEEP 10-24 cm H2O based on FiO2)",
            "  - FiO2 titrated to SpO2 88-95% or PaO2 55-80 mmHg",
            "  - Permissive hypercapnia acceptable (pH >7.20)",
            "",
            "MODERATE-SEVERE ARDS INTERVENTIONS:",
            "  - Prone positioning 12-16 hours/day (mortality benefit)",
            "  - Neuromuscular blockade early (first 48h) if severe",
            "",
            "REFRACTORY HYPOXEMIA:",
            "  - Inhaled pulmonary vasodilators (epoprostenol, nitric oxide)",
            "  - ECMO (VV-ECMO for oxygenation)",
            "",
            "CONSERVATIVE FLUID MANAGEMENT:",
            "  - Target CVP <4 mmHg or PAOP <8 mmHg when safe",
            "  - Diuretics if euvolemic",
            "",
            "SUPPORTIVE:",
            "  - Treat underlying cause (antibiotics for sepsis/pneumonia)",
            "  - DVT prophylaxis",
            "  - Stress ulcer prophylaxis",
            "  - Early enteral nutrition",
            "  - Sedation holidays, spontaneous breathing trials",
            "",
            "NO PROVEN BENEFIT (don't use routinely):",
            "  - Corticosteroids (controversial, may use if ARDS >14 days)",
            "  - High-frequency oscillatory ventilation",
            "  - Inhaled NO (temporary oxygenation only)"
        ],
        "prognosis": "Mortality 35-45% (varies by severity). Survivors often have persistent lung function and cognitive impairment. Recovery takes months.",
        "source": "ARDS Network Low Tidal Volume Trial; PROSEVA Prone Positioning Trial; FACTT Fluid Management Trial",
        "citations": [
            "ARDS Definition Task Force. Acute Respiratory Distress Syndrome: The Berlin Definition. JAMA. 2012;307:2526-2533",
            "Acute Respiratory Distress Syndrome Network. Ventilation with lower tidal volumes as compared with traditional tidal volumes for ALI and ARDS. N Engl J Med. 2000;342:1301-1308",
            "Guérin C, et al. Prone positioning in severe acute respiratory distress syndrome. N Engl J Med. 2013;368:2159-2168"
        ],
        "text": "Disease: ARDS | Description: Acute inflammatory lung injury with increased permeability, hypoxemia, bilateral opacities. Mortality 35-45%. Common in sepsis, pneumonia, aspiration, trauma. | Berlin criteria: onset <1 week, bilateral opacities, not cardiac origin, P/F ratio <300 on PEEP≥5. Severity: mild 200-300, moderate 100-200, severe <100 | Symptoms: rapid-onset severe dyspnea, tachypnea, refractory hypoxemia, cyanosis | Treatments: ARDSNet protocol - low tidal volume 6 mL/kg PBW, plateau pressure ≤30, high PEEP. Prone positioning if moderate-severe. ECMO if refractory. Conservative fluids. | Source: ARDS Network Low Tidal Volume Trial"
    })
    
    entries.append({
        "id": "MED:RESP:003",
        "name": "COPD Exacerbation",
        "description": "Acute exacerbation of COPD (AECOPD) is sustained worsening of respiratory symptoms beyond normal day-to-day variation, requiring change in medication. Leading cause of hospitalization in COPD patients. Mortality 3-4% inpatient, 10-20% if requiring ICU. Frequent exacerbations accelerate lung function decline.",
        "synonyms": ["COPD exacerbation", "AECOPD", "COPD flare", "acute COPD"],
        "related_synonyms": ["chronic bronchitis exacerbation", "emphysema exacerbation"],
        "category": "respiratory",
        "pathophysiology": "Airway inflammation and mucus hypersecretion worsen airflow obstruction. V/Q mismatch increases. Dynamic hyperinflation worsens dyspnea. Common triggers are respiratory infections (viral or bacterial) and air pollution.",
        "child_diseases": [],
        "symptoms": [
            "INCREASED from baseline:",
            "dyspnea (most common)",
            "cough",
            "sputum volume and/or purulence",
            "",
            "OTHER:",
            "wheezing",
            "chest tightness",
            "fever (if infectious)",
            "tachypnea",
            "accessory muscle use",
            "",
            "SEVERE EXACERBATION SIGNS:",
            "cyanosis",
            "confusion/altered mental status",
            "inability to speak in sentences",
            "marked accessory muscle use",
            "paradoxical breathing"
        ],
        "common_triggers": [
            "respiratory tract infections (50-70%)",
            "  - viral: rhinovirus, influenza, RSV",
            "  - bacterial: H. influenzae, S. pneumoniae, M. catarrhalis, Pseudomonas",
            "air pollution",
            "weather changes",
            "medication non-adherence",
            "unknown (30%)"
        ],
        "severity_classification": [
            "MILD: treated with SABAs only",
            "MODERATE: requires SABAs + antibiotics and/or oral corticosteroids",
            "SEVERE: requires hospitalization or ED visit"
        ],
        "diagnostics": [
            "pulse oximetry (SpO2 target 88-92%)",
            "arterial blood gas if severe (assess for hypercapnia, acidosis)",
            "chest X-ray (rule out pneumonia, pneumothorax)",
            "ECG (rule out cardiac cause, assess for arrhythmia)",
            "CBC (assess for leukocytosis, polycythemia)",
            "BMP (assess for electrolyte abnormalities)",
            "BNP/NT-proBNP (if heart failure suspected)",
            "sputum culture if severe or frequent exacerbations"
        ],
        "treatments": [
            "BRONCHODILATORS (mainstay):",
            "  - SABA: albuterol nebulizer 2.5mg q20min x3, then q1-4h",
            "  - SAMA: ipratropium nebulizer 0.5mg q4-6h",
            "  - OR combined albuterol/ipratropium (DuoNeb)",
            "",
            "SYSTEMIC CORTICOSTEROIDS:",
            "  - Prednisone 40mg daily x 5 days (no taper needed)",
            "  - OR IV methylprednisolone if unable to take PO",
            "",
            "ANTIBIOTICS (if increased sputum purulence):",
            "  - First-line: azithromycin, doxycycline, or amoxicillin-clavulanate x 5-7 days",
            "  - If risk for Pseudomonas: respiratory fluoroquinolone",
            "",
            "OXYGEN:",
            "  - Target SpO2 88-92% (avoid hyperoxia → hypercapnia)",
            "  - Use Venturi mask for precise FiO2",
            "",
            "NON-INVASIVE VENTILATION (NIV):",
            "  - Indicated for acute respiratory acidosis (pH <7.35, PaCO2 >45)",
            "  - BiPAP settings: IPAP 10-15, EPAP 4-5 cm H2O",
            "  - Reduces intubation and mortality",
            "",
            "INVASIVE MECHANICAL VENTILATION:",
            "  - If NIV fails or contraindicated",
            "  - If severe acidosis (pH <7.25), respiratory arrest, or coma",
            "",
            "ADDITIONAL:",
            "  - DVT prophylaxis",
            "  - Optimize nutrition",
            "  - Consider pulmonology consult if frequent exacerbations"
        ],
        "prevention": [
            "smoking cessation (most important)",
            "inhaled maintenance therapy (LABA, LAMA, ICS as appropriate)",
            "influenza and pneumococcal vaccination",
            "pulmonary rehabilitation",
            "azithromycin prophylaxis if frequent exacerbations"
        ],
        "source": "GOLD 2024 Report; ATS/ERS COPD Exacerbation Statement",
        "citations": [
            "Global Initiative for Chronic Obstructive Lung Disease (GOLD). Global Strategy for the Diagnosis, Management, and Prevention of COPD: 2024 Report.",
            "Wedzicha JA, et al. Management of COPD exacerbations: a European Respiratory Society/American Thoracic Society guideline. Eur Respir J. 2017;49:1600791",
            "Leuppi JD, et al. Short-term vs Conventional Glucocorticoid Therapy in Acute Exacerbations of COPD. JAMA. 2013;309:2223-2231"
        ],
        "text": "Disease: COPD Exacerbation | Description: Sustained worsening of respiratory symptoms requiring treatment change. Leading COPD hospitalization cause. Mortality 3-4% inpatient, 10-20% if ICU. Accelerates lung function decline. | Symptoms: increased dyspnea, cough, sputum volume/purulence, wheezing. Severe: cyanosis, confusion, accessory muscle use | Triggers: respiratory infections (50-70%), air pollution | Diagnostics: pulse ox, ABG if severe, CXR, ECG, CBC, BMP | Treatments: SABAs (albuterol q20min), corticosteroids (prednisone 40mg x5 days), antibiotics if purulent sputum, oxygen target 88-92%, NIV if acidotic. | Source: GOLD 2024"
    })
    
    # ==================== RENAL CONDITIONS ====================
    
    entries.append({
        "id": "MED:RENAL:001",
        "name": "Acute Kidney Injury",
        "description": "Acute kidney injury (AKI) is a rapid decline in kidney function over hours to days, characterized by rising creatinine and/or decreased urine output. Affects 10-15% of hospitalized patients, >50% of ICU patients. Associated with increased mortality, prolonged hospitalization, and risk of chronic kidney disease.",
        "synonyms": ["AKI", "acute renal failure", "ARF", "acute renal insufficiency"],
        "related_synonyms": ["prerenal azotemia", "intrinsic renal failure", "postrenal obstruction", "ATN"],
        "category": "nephrology/critical care",
        "pathophysiology": "Three main mechanisms: prerenal (decreased renal perfusion), intrinsic (direct kidney damage), postrenal (obstruction). Ischemia and nephrotoxins cause acute tubular necrosis (ATN), the most common intrinsic cause.",
        "child_diseases": [],
        "kdigo_criteria": [
            "STAGE 1:",
            "  - Creatinine increase ≥0.3 mg/dL within 48h OR",
            "  - Creatinine increase 1.5-1.9x baseline within 7 days OR",
            "  - Urine output <0.5 mL/kg/hr for 6-12 hours",
            "",
            "STAGE 2:",
            "  - Creatinine 2.0-2.9x baseline OR",
            "  - Urine output <0.5 mL/kg/hr for ≥12 hours",
            "",
            "STAGE 3:",
            "  - Creatinine ≥3.0x baseline OR",
            "  - Creatinine increase to ≥4.0 mg/dL OR",
            "  - Initiation of renal replacement therapy OR",
            "  - Urine output <0.3 mL/kg/hr for ≥24 hours OR anuria ≥12 hours"
        ],
        "symptoms": [
            "OFTEN ASYMPTOMATIC (discovered on labs)",
            "",
            "WHEN SYMPTOMATIC:",
            "decreased urine output (oliguria <400 mL/day)",
            "edema (peripheral, pulmonary)",
            "fatigue, weakness",
            "nausea, vomiting, anorexia",
            "confusion (uremic encephalopathy)",
            "shortness of breath (fluid overload, acidosis)",
            "",
            "SIGNS OF UREMIA (if severe):",
            "pericarditis (friction rub)",
            "asterixis",
            "seizures",
            "bleeding"
        ],
        "causes_by_category": [
            "PRERENAL (60-70%):",
            "  - Hypovolemia (hemorrhage, dehydration, GI losses)",
            "  - Decreased cardiac output (heart failure, MI)",
            "  - Systemic vasodilation (sepsis, cirrhosis)",
            "  - Renal vasoconstriction (NSAIDs, ACEi, contrast)",
            "",
            "INTRINSIC (25-35%):",
            "  - Acute tubular necrosis (ischemia or nephrotoxins - most common)",
            "  - Acute interstitial nephritis (drugs, infection)",
            "  - Glomerulonephritis",
            "  - Vascular (TTP/HUS, renal artery thrombosis)",
            "",
            "POSTRENAL (5-10%):",
            "  - BPH",
            "  - Kidney stones (bilateral or single kidney)",
            "  - Malignancy (bladder, prostate, cervical)",
            "  - Strictures"
        ],
        "diagnostics": [
            "serum creatinine (serial measurements)",
            "BUN (elevated, BUN:Cr ratio helps determine prerenal vs intrinsic)",
            "urinalysis with microscopy:",
            "  - Muddy brown casts → ATN",
            "  - RBC casts → glomerulonephritis",
            "  - WBC casts → interstitial nephritis",
            "  - Bland → prerenal or postrenal",
            "urine electrolytes:",
            "  - FeNa <1% → prerenal",
            "  - FeNa >2% → intrinsic (ATN)",
            "  - (FeNa unreliable with diuretics - use FeUrea instead)",
            "renal ultrasound (assess for hydronephrosis, size)",
            "CBC, electrolytes (hyperkalemia!), calcium, phosphorus",
            "kidney biopsy if diagnosis unclear and would change management"
        ],
        "treatments": [
            "GENERAL PRINCIPLES:",
            "  - Treat underlying cause",
            "  - Optimize volume status (fluids if prerenal, diuretics if overloaded)",
            "  - Avoid nephrotoxins (NSAIDs, aminoglycosides, contrast)",
            "  - Adjust medication doses for renal function",
            "",
            "PRERENAL:",
            "  - IV fluids (crystalloid) to restore perfusion",
            "  - Treat underlying cause (heart failure, sepsis)",
            "",
            "INTRINSIC (ATN):",
            "  - Supportive care (no specific treatment for ATN)",
            "  - Avoid additional insults",
            "  - May recover in 1-3 weeks",
            "",
            "POSTRENAL:",
            "  - Relieve obstruction (Foley catheter, nephrostomy, ureteral stent)",
            "  - Monitor for post-obstructive diuresis",
            "",
            "MANAGE COMPLICATIONS:",
            "  - Hyperkalemia: calcium gluconate, insulin/glucose, kayexalate, dialysis",
            "  - Acidosis: bicarbonate if severe (pH <7.1)",
            "  - Volume overload: diuretics or dialysis",
            "",
            "RENAL REPLACEMENT THERAPY (dialysis) INDICATIONS:",
            "  A - Acidosis (severe metabolic acidosis, pH <7.1)",
            "  E - Electrolytes (refractory hyperkalemia >6.5)",
            "  I - Intoxication (dialyzable toxins: methanol, ethylene glycol, lithium)",
            "  O - Overload (refractory pulmonary edema)",
            "  U - Uremia symptoms (encephalopathy, pericarditis, bleeding)"
        ],
        "prevention": [
            "avoid nephrotoxins in high-risk patients",
            "pre-hydration before contrast",
            "hold ACEi/ARB during acute illness",
            "monitor kidney function in hospitalized patients"
        ],
        "source": "KDIGO Clinical Practice Guideline for Acute Kidney Injury 2012; 2024 Update",
        "citations": [
            "Kidney Disease: Improving Global Outcomes (KDIGO) Acute Kidney Injury Work Group. KDIGO Clinical Practice Guideline for Acute Kidney Injury. Kidney Int Suppl. 2012;2:1-138",
            "Ronco C, et al. Acute kidney injury. Lancet. 2019;394:1949-1964",
            "Kellum JA, et al. Acute kidney injury. Nat Rev Dis Primers. 2021;7:52"
        ],
        "text": "Disease: Acute Kidney Injury | Description: Rapid kidney function decline over hours-days. Affects 10-15% hospitalized, >50% ICU patients. Increases mortality and CKD risk. | KDIGO Staging: Cr increase ≥0.3 in 48h or 1.5x baseline, or decreased urine output | Symptoms: often asymptomatic. When symptomatic: oliguria, edema, fatigue, nausea, confusion | Causes: Prerenal 60-70% (hypovolemia, heart failure, sepsis), Intrinsic 25-35% (ATN, AIN), Postrenal 5-10% (BPH, stones) | Diagnostics: Cr, BUN, urinalysis with microscopy, urine electrolytes (FeNa), renal US | Treatments: Treat cause. Prerenal-fluids. Postrenal-relieve obstruction. Dialysis if AEIOU (Acidosis, Electrolytes, Intoxication, Overload, Uremia) | Source: KDIGO AKI Guidelines"
    })
    
    entries.append({
        "id": "MED:RENAL:002",
        "name": "Chronic Kidney Disease",
        "description": "Chronic kidney disease (CKD) is progressive loss of kidney function over months to years. Defined as eGFR <60 mL/min/1.73m² or markers of kidney damage for ≥3 months. Affects 15% of US adults (37 million). Leading causes are diabetes and hypertension. Increases cardiovascular mortality risk 5-10 fold.",
        "synonyms": ["CKD", "chronic renal failure", "chronic renal insufficiency", "chronic kidney failure"],
        "related_synonyms": ["ESRD", "end-stage renal disease", "kidney failure"],
        "category": "nephrology",
        "pathophysiology": "Progressive nephron loss from various causes leads to compensatory hyperfiltration in remaining nephrons, which paradoxically accelerates further damage. Results in inability to maintain fluid, electrolyte, and acid-base balance, and failure of endocrine functions (erythropoietin, vitamin D activation).",
        "child_diseases": [],
        "staging": [
            "STAGE 1: eGFR ≥90 with kidney damage (albuminuria, structural abnormality)",
            "STAGE 2: eGFR 60-89 with kidney damage",
            "STAGE 3a: eGFR 45-59",
            "STAGE 3b: eGFR 30-44",
            "STAGE 4: eGFR 15-29",
            "STAGE 5: eGFR <15 (kidney failure, may need dialysis/transplant)",
            "",
            "ALBUMINURIA CATEGORIES:",
            "A1: UACR <30 mg/g (normal to mildly increased)",
            "A2: UACR 30-300 mg/g (moderately increased, microalbuminuria)",
            "A3: UACR >300 mg/g (severely increased, macroalbuminuria)"
        ],
        "symptoms": [
            "EARLY CKD: usually asymptomatic",
            "",
            "ADVANCED CKD (Stage 4-5):",
            "fatigue, weakness",
            "anorexia, nausea, vomiting",
            "pruritus (itching)",
            "edema (peripheral, periorbital)",
            "dyspnea (fluid overload or anemia)",
            "cognitive impairment",
            "sleep disturbances, restless legs",
            "muscle cramps",
            "hiccups",
            "",
            "UREMIC SYMPTOMS (ESRD):",
            "asterixis",
            "uremic frost",
            "pericarditis",
            "encephalopathy"
        ],
        "common_causes": [
            "diabetic nephropathy (45% of ESRD)",
            "hypertensive nephrosclerosis (30%)",
            "glomerulonephritis",
            "polycystic kidney disease",
            "obstructive uropathy",
            "reflux nephropathy",
            "lupus nephritis",
            "analgesic nephropathy"
        ],
        "complications": [
            "cardiovascular disease (leading cause of death)",
            "anemia (EPO deficiency)",
            "mineral and bone disorder (CKD-MBD):",
            "  - hyperphosphatemia",
            "  - hypocalcemia",
            "  - secondary hyperparathyroidism",
            "  - renal osteodystrophy",
            "metabolic acidosis",
            "hyperkalemia",
            "volume overload",
            "uremic syndrome"
        ],
        "diagnostics": [
            "serum creatinine and eGFR (CKD-EPI equation)",
            "urine albumin-to-creatinine ratio (UACR)",
            "urinalysis",
            "CBC (anemia)",
            "BMP (electrolytes, BUN)",
            "calcium, phosphorus, PTH, vitamin D",
            "lipid panel",
            "renal ultrasound",
            "kidney biopsy if diagnosis unclear and would change management"
        ],
        "treatments": [
            "SLOW PROGRESSION:",
            "  - Blood pressure control (<130/80 mmHg)",
            "  - ACE inhibitor or ARB (especially if albuminuria)",
            "  - SGLT2 inhibitor (dapagliflozin, empagliflozin) - renal protective even without DM",
            "  - Finerenone (non-steroidal MRA) for diabetic kidney disease",
            "  - Glycemic control if diabetic (HbA1c <7%)",
            "  - Protein restriction (0.8 g/kg/day if advanced CKD)",
            "",
            "MANAGE COMPLICATIONS:",
            "  - Anemia: erythropoietin-stimulating agents (ESA), iron supplementation",
            "  - CKD-MBD: phosphate binders, vitamin D (calcitriol or analogs), calcimimetics",
            "  - Acidosis: sodium bicarbonate",
            "  - Hyperkalemia: low-K diet, kayexalate, patiromer",
            "  - Volume overload: sodium restriction, diuretics",
            "",
            "CARDIOVASCULAR RISK REDUCTION:",
            "  - Statin therapy",
            "  - Aspirin for secondary prevention",
            "  - Smoking cessation",
            "",
            "RENAL REPLACEMENT THERAPY (Stage 5):",
            "  - Hemodialysis",
            "  - Peritoneal dialysis",
            "  - Kidney transplant (best option if eligible)",
            "",
            "AVOID NEPHROTOXINS:",
            "  - NSAIDs",
            "  - Aminoglycosides",
            "  - IV contrast (if necessary, use low volume with hydration)"
        ],
        "referral_to_nephrology": [
            "eGFR <30 (Stage 4)",
            "rapidly declining eGFR (>5 mL/min/year)",
            "persistent proteinuria (UACR >300)",
            "refractory hypertension",
            "unclear etiology",
            "preparation for dialysis/transplant"
        ],
        "source": "KDIGO 2024 Clinical Practice Guideline for CKD Evaluation and Management",
        "citations": [
            "Kidney Disease: Improving Global Outcomes (KDIGO) CKD Work Group. KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease. Kidney Int. 2024;105(4S):S117-S314",
            "Heerspink HJL, et al. Dapagliflozin in Patients with Chronic Kidney Disease. N Engl J Med. 2020;383:1436-1446",
            "Bakris GL, et al. Effect of Finerenone on Chronic Kidney Disease Outcomes in Type 2 Diabetes. N Engl J Med. 2020;383:2219-2229"
        ],
        "text": "Disease: Chronic Kidney Disease | Description: Progressive kidney function loss over months-years. eGFR <60 or kidney damage markers ≥3 months. Affects 15% of US adults. Diabetes and hypertension are leading causes. 5-10x increased CV mortality. | Staging: 1 (≥90 with damage), 2 (60-89), 3a (45-59), 3b (30-44), 4 (15-29), 5 (<15 - may need RRT) | Symptoms: Early asymptomatic. Advanced: fatigue, nausea, pruritus, edema, dyspnea, cognitive changes | Complications: CV disease, anemia, CKD-MBD, acidosis, hyperkalemia | Treatments: ACEi/ARB + SGLT2i for slowing progression. Manage anemia (ESA), CKD-MBD (phosphate binders, vitamin D). RRT for Stage 5 (dialysis or transplant) | Source: KDIGO CKD Guidelines 2024"
    })
    
    # ==================== INFECTIOUS DISEASE ====================
    
    entries.append({
        "id": "MED:ID:001",
        "name": "Meningitis",
        "description": "Meningitis is inflammation of the meninges surrounding the brain and spinal cord. Bacterial meningitis is a medical emergency with mortality 15-25% even with treatment. Viral meningitis is more common but usually self-limited. Key pathogens vary by age and immune status. Classic triad: fever, neck stiffness, altered mental status - present in only 45% of cases.",
        "synonyms": ["meningoencephalitis", "brain infection", "spinal meningitis"],
        "related_synonyms": ["bacterial meningitis", "viral meningitis", "aseptic meningitis", "tuberculous meningitis"],
        "category": "infectious disease/neurology",
        "pathophysiology": "Pathogens reach meninges via hematogenous spread, direct extension (sinusitis, otitis), or disrupted barriers (trauma, surgery). Inflammation causes increased intracranial pressure, cerebral edema, and neuronal injury.",
        "child_diseases": [],
        "common_pathogens": [
            "BACTERIAL (by age):",
            "Neonates: Group B Streptococcus, E. coli, Listeria",
            "2 months - 50 years: S. pneumoniae, N. meningitidis",
            ">50 years: S. pneumoniae, N. meningitidis, Listeria, Gram-negatives",
            "Immunocompromised: Add Listeria, Cryptococcus, TB",
            "Post-neurosurgery: S. aureus, Gram-negatives",
            "",
            "VIRAL:",
            "Enteroviruses (most common)",
            "HSV-2 (Mollaret's meningitis)",
            "Arboviruses (West Nile)",
            "HIV",
            "",
            "OTHER:",
            "Mycobacterium tuberculosis",
            "Cryptococcus neoformans",
            "Fungal (Coccidioides, Histoplasma)"
        ],
        "symptoms": [
            "CLASSIC TRIAD (only 45% have all 3):",
            "fever",
            "neck stiffness (nuchal rigidity)",
            "altered mental status",
            "",
            "OTHER SYMPTOMS:",
            "severe headache",
            "photophobia",
            "nausea and vomiting",
            "seizures",
            "focal neurological deficits",
            "",
            "PHYSICAL EXAM SIGNS:",
            "Kernig sign (pain/resistance with knee extension when hip flexed)",
            "Brudzinski sign (hip/knee flexion with passive neck flexion)",
            "petechial or purpuric rash (suggests N. meningitidis)",
            "",
            "NEONATES AND ELDERLY:",
            "may present only with irritability, lethargy, poor feeding, fever"
        ],
        "diagnostics": [
            "LUMBAR PUNCTURE (gold standard):",
            "  Bacterial: elevated WBC (>1000, PMN predominant), low glucose (<40 or <2/3 serum), high protein (>250)",
            "  Viral: elevated WBC (10-500, lymphocyte predominant), normal glucose, normal-mildly elevated protein",
            "",
            "CSF studies:",
            "  - Gram stain and culture",
            "  - Cell count and differential",
            "  - Glucose and protein",
            "  - Latex agglutination or PCR for specific pathogens",
            "  - HSV PCR if encephalitis suspected",
            "  - Cryptococcal antigen if immunocompromised",
            "",
            "Blood cultures (before antibiotics)",
            "CBC, BMP, coagulation studies",
            "",
            "CT HEAD BEFORE LP IF:",
            "  - Immunocompromised",
            "  - History of CNS disease",
            "  - New seizure within 1 week",
            "  - Papilledema",
            "  - Altered consciousness",
            "  - Focal neurological deficit"
        ],
        "treatments": [
            "EMPIRIC ANTIBIOTICS (start immediately, don't wait for LP results):",
            "",
            "Adults <50 years:",
            "  - Ceftriaxone 2g IV q12h + Vancomycin 15-20mg/kg IV q8-12h",
            "",
            "Adults >50 years or immunocompromised:",
            "  - Ceftriaxone 2g IV q12h + Vancomycin + Ampicillin 2g IV q4h (for Listeria)",
            "",
            "DEXAMETHASONE (for bacterial meningitis):",
            "  - 0.15 mg/kg IV q6h x 4 days",
            "  - Give BEFORE or WITH first antibiotic dose",
            "  - Reduces mortality and neurological sequelae (especially for S. pneumoniae)",
            "",
            "DURATION:",
            "  - S. pneumoniae: 10-14 days",
            "  - N. meningitidis: 7 days",
            "  - Listeria: 21 days",
            "  - Gram-negative: 21 days",
            "",
            "VIRAL MENINGITIS:",
            "  - Supportive care",
            "  - HSV encephalitis: Acyclovir 10mg/kg IV q8h x 14-21 days",
            "",
            "CHEMOPROPHYLAXIS FOR N. MENINGITIDIS CONTACTS:",
            "  - Ciprofloxacin 500mg PO x1 OR",
            "  - Rifampin 600mg PO q12h x 2 days OR",
            "  - Ceftriaxone 250mg IM x1"
        ],
        "complications": [
            "hearing loss (up to 30%)",
            "seizures",
            "hydrocephalus",
            "cerebral infarction",
            "cognitive impairment",
            "cranial nerve palsies",
            "death (15-25% bacterial)"
        ],
        "prevention": [
            "vaccination:",
            "  - Pneumococcal (PCV13, PPSV23)",
            "  - Meningococcal (MenACWY, MenB)",
            "  - Haemophilus influenzae type b (Hib)"
        ],
        "source": "IDSA Guidelines for Healthcare-Associated Meningitis and Ventriculitis 2017; Tunkel AR et al.",
        "citations": [
            "Tunkel AR, et al. Practice Guidelines for the Management of Bacterial Meningitis. Clin Infect Dis. 2004;39:1267-1284",
            "van de Beek D, et al. Clinical features and prognostic factors in adults with bacterial meningitis. N Engl J Med. 2004;351:1849-1859",
            "Brouwer MC, et al. Dilemmas in the diagnosis of acute community-acquired bacterial meningitis. Lancet. 2012;380:1684-1692"
        ],
        "text": "Disease: Meningitis | Description: Meningeal inflammation. Bacterial meningitis is emergency with 15-25% mortality. Viral more common but self-limited. Classic triad (fever, neck stiffness, AMS) only in 45%. | Common pathogens: S. pneumoniae, N. meningitidis, Listeria (elderly/immunocompromised), enteroviruses (viral) | Symptoms: headache, fever, neck stiffness, altered mental status, photophobia, vomiting, petechial rash (meningococcal), Kernig/Brudzinski signs | Diagnostics: Lumbar puncture (WBC, glucose, protein, Gram stain, culture). CT before LP if focal deficits, immunocompromised, papilledema | Treatments: Empiric ceftriaxone+vancomycin (add ampicillin if >50/immunocompromised for Listeria). Dexamethasone before/with first antibiotic. Acyclovir for HSV | Source: IDSA Bacterial Meningitis Guidelines"
    })
    
    entries.append({
        "id": "MED:ID:002",
        "name": "Infective Endocarditis",
        "description": "Infective endocarditis (IE) is infection of the heart valves or endocardium. High mortality (15-30%) despite treatment. Risk factors include IV drug use, prosthetic valves, structural heart disease, and poor dentition. Requires prolonged IV antibiotic therapy (4-6 weeks) and often surgery.",
        "synonyms": ["IE", "bacterial endocarditis", "subacute bacterial endocarditis", "SBE"],
        "related_synonyms": ["native valve endocarditis", "prosthetic valve endocarditis", "right-sided endocarditis"],
        "category": "infectious disease/cardiology",
        "pathophysiology": "Bacteremia seeds damaged or abnormal endocardium, forming vegetations (masses of platelets, fibrin, and microorganisms). Vegetations cause local valve destruction and can embolize to distant organs.",
        "child_diseases": [],
        "common_pathogens": [
            "NATIVE VALVE:",
            "  - Staphylococcus aureus (most common overall, especially IVDU)",
            "  - Viridans group streptococci (oral flora, subacute)",
            "  - Enterococcus faecalis",
            "  - Streptococcus gallolyticus (associated with colon cancer!)",
            "  - HACEK organisms (rare)",
            "",
            "PROSTHETIC VALVE:",
            "  - Early (<60 days): S. aureus, coagulase-negative staph, Gram-negatives",
            "  - Late: similar to native valve",
            "",
            "IV DRUG USE:",
            "  - S. aureus (right-sided, tricuspid valve)",
            "  - Pseudomonas, Candida"
        ],
        "modified_duke_criteria": [
            "DEFINITE IE: 2 major, or 1 major + 3 minor, or 5 minor",
            "",
            "MAJOR CRITERIA:",
            "1. Positive blood cultures:",
            "   - Typical organism from 2 separate cultures, OR",
            "   - Persistently positive blood cultures",
            "2. Evidence of endocardial involvement:",
            "   - Echocardiogram: vegetation, abscess, new valvular regurgitation, OR",
            "   - New dehiscence of prosthetic valve",
            "",
            "MINOR CRITERIA:",
            "- Predisposing heart condition or IVDU",
            "- Fever ≥38°C",
            "- Vascular phenomena (emboli, mycotic aneurysm, Janeway lesions)",
            "- Immunologic phenomena (glomerulonephritis, Osler nodes, Roth spots)",
            "- Positive blood culture not meeting major criteria"
        ],
        "symptoms": [
            "ACUTE (days, usually S. aureus):",
            "high fever, rigors",
            "rapid deterioration",
            "",
            "SUBACUTE (weeks, usually streptococci):",
            "low-grade fever",
            "malaise, fatigue",
            "weight loss",
            "night sweats",
            "",
            "CARDIAC:",
            "new or changing murmur",
            "heart failure (valve destruction)",
            "",
            "EMBOLIC PHENOMENA:",
            "stroke, TIA",
            "mycotic aneurysm",
            "splenic infarct",
            "pulmonary emboli (right-sided IE)",
            "renal infarcts",
            "",
            "PERIPHERAL SIGNS:",
            "Janeway lesions (painless erythematous lesions on palms/soles)",
            "Osler nodes (painful nodules on fingers/toes)",
            "splinter hemorrhages (nail bed)",
            "Roth spots (retinal hemorrhages)"
        ],
        "diagnostics": [
            "BLOOD CULTURES (3 sets from different sites before antibiotics)",
            "  - Should not wait if unstable, but cultures before ABx if possible",
            "",
            "ECHOCARDIOGRAM:",
            "  - TTE first (sensitivity 50-70%)",
            "  - TEE if TTE negative but high suspicion (sensitivity 90-95%)",
            "  - TEE preferred for prosthetic valves",
            "",
            "Additional:",
            "  - CBC (anemia, leukocytosis)",
            "  - BMP (renal function)",
            "  - Urinalysis (hematuria, proteinuria)",
            "  - CRP, ESR",
            "  - CT head if neurological symptoms",
            "  - CT chest if septic pulmonary emboli"
        ],
        "treatments": [
            "NATIVE VALVE (empiric while awaiting cultures):",
            "  - Vancomycin + Ceftriaxone (covers staph, strep, enterococci)",
            "",
            "PROSTHETIC VALVE (empiric):",
            "  - Vancomycin + Gentamicin + Rifampin",
            "",
            "PATHOGEN-DIRECTED THERAPY (adjust when cultures available):",
            "  - MSSA: Nafcillin or oxacillin 2g IV q4h x 6 weeks",
            "  - MRSA: Vancomycin 15-20mg/kg IV q8-12h x 6 weeks (add rifampin for prosthetic)",
            "  - Streptococci (penicillin-sensitive): Penicillin G or ceftriaxone x 4 weeks",
            "  - Enterococci: Ampicillin + gentamicin (or ceftriaxone) x 4-6 weeks",
            "",
            "DURATION:",
            "  - Native valve: 4-6 weeks",
            "  - Prosthetic valve: 6+ weeks",
            "",
            "SURGICAL INDICATIONS:",
            "  - Heart failure from valve dysfunction",
            "  - Uncontrolled infection despite antibiotics",
            "  - Large (>10mm) mobile vegetation",
            "  - Abscess or fistula",
            "  - Fungal or highly resistant organism",
            "  - Prosthetic valve infection with relapse"
        ],
        "prevention": [
            "antibiotic prophylaxis before dental procedures for:",
            "  - prosthetic valves",
            "  - previous IE",
            "  - congenital heart disease (specific types)",
            "  - cardiac transplant with valvulopathy",
            "",
            "Prophylaxis regimen: Amoxicillin 2g PO 30-60 min before procedure"
        ],
        "source": "2015 AHA/ACC Guidelines for Infective Endocarditis; 2023 ESC Guidelines for IE",
        "citations": [
            "Baddour LM, et al. Infective Endocarditis in Adults: Diagnosis, Antimicrobial Therapy, and Management of Complications. Circulation. 2015;132:1435-1486",
            "Habib G, et al. 2015 ESC Guidelines for the management of infective endocarditis. Eur Heart J. 2015;36:3075-3128",
            "Delgado V, et al. 2023 ESC Guidelines for the management of endocarditis. Eur Heart J. 2023;44:3948-4042"
        ],
        "text": "Disease: Infective Endocarditis | Description: Infection of heart valves/endocardium. Mortality 15-30%. Requires prolonged IV antibiotics (4-6 weeks), often surgery. | Common pathogens: S. aureus (most common, especially IVDU), viridans strep, enterococci. S. gallolyticus → screen for colon cancer | Duke Criteria: 2 major (positive cultures, echo findings) or combinations with minor criteria | Symptoms: fever, new murmur, embolic phenomena (stroke, splenic infarct), Janeway lesions, Osler nodes, splinter hemorrhages | Diagnostics: 3 sets blood cultures, TTE/TEE | Treatments: Empiric vancomycin+ceftriaxone. Directed therapy 4-6 weeks. Surgery if heart failure, uncontrolled infection, large vegetation, abscess | Source: 2015 AHA IE Guidelines"
    })
    
    entries.append({
        "id": "MED:ID:003",
        "name": "Clostridioides difficile Infection",
        "description": "Clostridioides difficile infection (CDI) is toxin-mediated colitis caused by C. difficile, typically following antibiotic exposure. Most common healthcare-associated infection. Recurrence rate 20-30%. Spectrum ranges from mild diarrhea to fulminant colitis with toxic megacolon. Annual US healthcare costs exceed $5 billion.",
        "synonyms": ["C. diff", "C. difficile colitis", "CDI", "pseudomembranous colitis", "antibiotic-associated colitis"],
        "related_synonyms": ["CDAD", "Clostridium difficile infection"],
        "category": "infectious disease/gastroenterology",
        "pathophysiology": "Antibiotics disrupt normal gut flora, allowing C. difficile (acquired from environment or endogenous spores) to proliferate. Toxins A and B cause epithelial damage, inflammation, and secretory diarrhea. Hypervirulent strain NAP1/BI/027 produces more toxin and has higher mortality.",
        "child_diseases": [],
        "risk_factors": [
            "antibiotic exposure (highest risk: fluoroquinolones, clindamycin, cephalosporins)",
            "age >65 years",
            "hospitalization or long-term care facility",
            "recent hospitalization (within 3 months)",
            "immunosuppression",
            "inflammatory bowel disease",
            "gastric acid suppression (PPIs - controversial)",
            "chemotherapy",
            "gastrointestinal surgery or manipulation"
        ],
        "symptoms": [
            "MILD-MODERATE:",
            "watery diarrhea (≥3 unformed stools in 24 hours)",
            "lower abdominal cramping",
            "low-grade fever",
            "",
            "SEVERE:",
            "profuse diarrhea (10-15 episodes/day)",
            "severe abdominal pain and distension",
            "high fever",
            "leukocytosis (WBC >15,000, can be >40,000)",
            "elevated creatinine",
            "hypoalbuminemia",
            "",
            "FULMINANT (life-threatening):",
            "hypotension/shock",
            "ileus (may have decreased diarrhea due to ileus)",
            "toxic megacolon (colon dilation >6cm)",
            "mental status changes",
            "end-organ failure"
        ],
        "severity_classification": [
            "NON-SEVERE: WBC ≤15,000 AND creatinine <1.5 mg/dL",
            "SEVERE: WBC >15,000 OR creatinine ≥1.5 (or 1.5x baseline)",
            "FULMINANT: hypotension, shock, ileus, or megacolon"
        ],
        "diagnostics": [
            "STOOL TESTING (unformed stool only):",
            "  - NAAT (PCR) for toxin genes (highly sensitive)",
            "  - Toxin EIA (enzyme immunoassay) for toxins A/B",
            "  - GDH (glutamate dehydrogenase) antigen",
            "  - Two-step: GDH + toxin EIA, reflex to NAAT if discordant",
            "",
            "DO NOT test formed stools or test of cure",
            "",
            "Laboratory:",
            "  - CBC (leukocytosis, may be very high)",
            "  - BMP (creatinine, electrolytes)",
            "  - Lactate (if severe)",
            "  - Albumin",
            "",
            "Imaging (if severe/fulminant):",
            "  - CT abdomen (colonic wall thickening, megacolon)",
            "  - Abdominal X-ray"
        ],
        "treatments": [
            "STOP THE INCITING ANTIBIOTIC IF POSSIBLE",
            "",
            "INITIAL EPISODE:",
            "  Non-severe: Fidaxomicin 200mg PO BID x 10 days (preferred)",
            "    OR Vancomycin 125mg PO QID x 10 days",
            "",
            "  Severe: Fidaxomicin 200mg PO BID x 10 days",
            "    OR Vancomycin 125mg PO QID x 10 days",
            "",
            "  Fulminant:",
            "    - Vancomycin 500mg PO/NG QID",
            "    - PLUS Vancomycin 500mg rectal enema q6h (if ileus)",
            "    - PLUS Metronidazole 500mg IV q8h",
            "    - Surgical consultation for possible colectomy",
            "",
            "RECURRENT CDI (first recurrence):",
            "  - Fidaxomicin 200mg BID x 10 days, then 200mg every other day x 20 days (extended pulsed)",
            "  - OR Vancomycin taper/pulse regimen",
            "  - Bezlotoxumab (monoclonal antibody vs toxin B) - reduces recurrence",
            "",
            "RECURRENT CDI (second or later recurrence):",
            "  - Fecal microbiota transplant (FMT) - 85-90% efficacy",
            "  - SER-109 (FDA-approved fecal microbiota product)",
            "",
            "SUPPORTIVE:",
            "  - IV fluids, electrolyte repletion",
            "  - Avoid antidiarrheals (loperamide) - controversial",
            "  - Avoid opioids if possible"
        ],
        "infection_control": [
            "contact precautions",
            "hand hygiene with soap and water (alcohol doesn't kill spores)",
            "private room",
            "dedicated equipment",
            "environmental cleaning with sporicidal agents"
        ],
        "source": "IDSA/SHEA Clinical Practice Guidelines for CDI 2021",
        "citations": [
            "Johnson S, et al. Clinical Practice Guideline by the IDSA and SHEA: 2021 Focused Update Guidelines on Management of CDI in Adults. Clin Infect Dis. 2021;73:e1029-e1044",
            "McDonald LC, et al. Clinical Practice Guidelines for CDI in Adults and Children: 2017 Update by IDSA and SHEA. Clin Infect Dis. 2018;66:e1-e48",
            "Kelly CP. Can we identify patients at high risk of recurrent Clostridium difficile infection? Clin Microbiol Infect. 2012;18 Suppl 6:21-27"
        ],
        "text": "Disease: C. difficile Infection | Description: Toxin-mediated colitis after antibiotic exposure. Most common healthcare-associated infection. 20-30% recurrence rate. Spectrum from mild diarrhea to toxic megacolon. | Risk factors: antibiotics (FQs, clindamycin, cephalosporins), age >65, hospitalization, immunosuppression, PPIs | Severity: Non-severe (WBC≤15k, Cr<1.5), Severe (WBC>15k or Cr≥1.5), Fulminant (shock, ileus, megacolon) | Symptoms: watery diarrhea ≥3/day, cramping, fever, leukocytosis. Fulminant: shock, ileus | Diagnostics: Stool PCR or 2-step testing. Do not test formed stool. | Treatments: Fidaxomicin or oral vancomycin 10 days. Fulminant: vanco PO/rectal + IV metronidazole + surgical consult. Recurrent: FMT highly effective | Source: IDSA/SHEA CDI Guidelines 2021"
    })
    
    # ==================== ADDITIONAL CRITICAL CONDITIONS ====================
    
    entries.append({
        "id": "MED:HEME:001",
        "name": "Disseminated Intravascular Coagulation",
        "description": "Disseminated intravascular coagulation (DIC) is a syndrome of systemic intravascular activation of coagulation leading to widespread fibrin deposition, microvascular thrombosis, and consumption of clotting factors and platelets. Always secondary to underlying disease. Acute DIC causes bleeding; chronic DIC causes thrombosis. Mortality 40-80% depending on underlying cause.",
        "synonyms": ["DIC", "consumptive coagulopathy", "defibrination syndrome"],
        "related_synonyms": ["acute DIC", "chronic DIC", "compensated DIC"],
        "category": "hematology/critical care",
        "pathophysiology": "Tissue factor release triggers coagulation cascade systemically. Massive thrombin generation causes widespread fibrin deposition in microvasculature (microthrombi, organ damage) and consumption of clotting factors and platelets (bleeding). Secondary fibrinolysis generates D-dimer.",
        "child_diseases": [],
        "underlying_causes": [
            "INFECTION/SEPSIS (most common, 30-40%)",
            "MALIGNANCY:",
            "  - Acute promyelocytic leukemia (APL)",
            "  - Solid tumors (prostate, pancreas, lung)",
            "TRAUMA/BURNS",
            "OBSTETRIC:",
            "  - Placental abruption",
            "  - Amniotic fluid embolism",
            "  - HELLP syndrome",
            "  - Retained dead fetus",
            "VASCULAR ABNORMALITIES (giant hemangioma, aortic aneurysm)",
            "SEVERE TRANSFUSION REACTIONS",
            "TOXIC/IMMUNOLOGIC REACTIONS (snake bites, drugs)"
        ],
        "symptoms": [
            "ACUTE DIC (bleeding predominates):",
            "petechiae and purpura",
            "bleeding from IV sites, surgical wounds",
            "mucosal bleeding (gums, GI, urinary)",
            "internal bleeding",
            "",
            "THROMBOTIC MANIFESTATIONS:",
            "skin necrosis (purpura fulminans)",
            "digital gangrene",
            "organ dysfunction (renal, hepatic, pulmonary)",
            "altered mental status",
            "",
            "CHRONIC DIC (thrombosis predominates):",
            "venous/arterial thromboembolism",
            "Trousseau syndrome (migratory thrombophlebitis in malignancy)"
        ],
        "diagnostics": [
            "NO single diagnostic test - combination of findings",
            "",
            "CLASSIC LAB FINDINGS:",
            "  - Prolonged PT and PTT",
            "  - Thrombocytopenia (platelet count decreasing)",
            "  - Low fibrinogen (<100 mg/dL suggests severe)",
            "  - Elevated D-dimer or FDP (very sensitive)",
            "  - Schistocytes on blood smear (microangiopathic hemolysis)",
            "",
            "ISTH DIC SCORING SYSTEM:",
            "  - Platelet count",
            "  - D-dimer/FDP",
            "  - Prolonged PT",
            "  - Fibrinogen level",
            "  - Score ≥5 = overt DIC",
            "",
            "Repeat labs serially to assess trend"
        ],
        "treatments": [
            "TREAT UNDERLYING CAUSE (most important):",
            "  - Antibiotics and source control for sepsis",
            "  - Delivery in obstetric causes",
            "  - Chemotherapy for APL (ATRA + arsenic)",
            "  - Remove triggering factor",
            "",
            "SUPPORTIVE TRANSFUSION (for active bleeding):",
            "  - Platelets: if <50,000 and bleeding (or <20,000 prophylactically)",
            "  - FFP: if PT/PTT prolonged >1.5x normal and bleeding",
            "  - Cryoprecipitate: if fibrinogen <100 mg/dL",
            "  - RBCs: if significant blood loss",
            "",
            "ANTICOAGULATION (controversial, mainly for chronic DIC):",
            "  - Heparin may be considered if thrombosis predominates",
            "  - Generally avoid in acute DIC with active bleeding",
            "",
            "DO NOT give antifibrinolytics (TXA) in DIC - promotes thrombosis"
        ],
        "prognosis": "Mortality 40-80% depending on underlying cause and severity. Better prognosis if underlying cause is treatable.",
        "source": "ISTH Guidance on DIC Diagnosis and Management; British Committee for Standards in Haematology Guidelines",
        "citations": [
            "Taylor FB, et al. Towards definition, clinical and laboratory criteria, and a scoring system for disseminated intravascular coagulation. Thromb Haemost. 2001;86:1327-1330",
            "Levi M, Scully M. How I treat disseminated intravascular coagulation. Blood. 2018;131:845-854",
            "Wada H, et al. Guidance for diagnosis and treatment of disseminated intravascular coagulation from harmonization of the recommendations from three guidelines. J Thromb Haemost. 2013;11:761-767"
        ],
        "text": "Disease: Disseminated Intravascular Coagulation | Description: Systemic coagulation activation causing fibrin deposition, microthrombi, and consumption of factors/platelets. Always secondary to underlying disease. Acute DIC causes bleeding; chronic causes thrombosis. Mortality 40-80%. | Causes: sepsis (most common), malignancy (APL), trauma, obstetric complications | Symptoms: Acute - petechiae, bleeding from all sites, purpura fulminans. Chronic - thromboembolism | Diagnostics: prolonged PT/PTT, thrombocytopenia, low fibrinogen, elevated D-dimer, schistocytes. ISTH score ≥5. | Treatments: TREAT UNDERLYING CAUSE. Transfusions for bleeding (platelets if <50k, FFP, cryo if fibrinogen<100). Avoid antifibrinolytics | Source: ISTH DIC Guidance"
    })
    
    entries.append({
        "id": "MED:TOX:001",
        "name": "Opioid Overdose",
        "description": "Opioid overdose is a life-threatening emergency characterized by respiratory depression, altered mental status, and miosis. Over 80,000 opioid-related deaths annually in US (2021). Can occur with prescription opioids, heroin, or synthetic opioids (fentanyl). Naloxone is the antidote and can reverse effects within minutes.",
        "synonyms": ["opioid toxicity", "narcotic overdose", "heroin overdose", "opioid poisoning"],
        "related_synonyms": ["fentanyl overdose", "morphine overdose", "oxycodone overdose"],
        "category": "toxicology/emergency medicine",
        "pathophysiology": "Opioids bind mu receptors in brainstem, suppressing respiratory drive. Respiratory depression leads to hypoxemia, hypercapnia, and respiratory acidosis. Can progress to respiratory arrest and death within minutes, especially with synthetic opioids like fentanyl.",
        "child_diseases": [],
        "classic_triad": [
            "1. Respiratory depression (RR <12, shallow breathing, apnea)",
            "2. Altered mental status (sedation, obtundation, coma)",
            "3. Miosis (pinpoint pupils)"
        ],
        "symptoms": [
            "RESPIRATORY:",
            "slow, shallow breathing (RR <12)",
            "apnea",
            "cyanosis",
            "agonal breathing (gasping)",
            "",
            "NEUROLOGICAL:",
            "decreased level of consciousness",
            "pinpoint pupils (miosis)",
            "seizures (with meperidine, tramadol, or hypoxia)",
            "",
            "CARDIOVASCULAR:",
            "bradycardia",
            "hypotension",
            "",
            "OTHER:",
            "hypothermia",
            "decreased bowel sounds",
            "urinary retention"
        ],
        "differential": [
            "other sedative overdose (benzodiazepines, barbiturates)",
            "hypoglycemia",
            "pontine stroke (also causes pinpoint pupils)",
            "hepatic encephalopathy",
            "postictal state"
        ],
        "diagnostics": [
            "CLINICAL DIAGNOSIS - don't delay treatment",
            "",
            "Supportive tests:",
            "  - Pulse oximetry",
            "  - Blood glucose (rule out hypoglycemia)",
            "  - ABG if severe",
            "  - Urine drug screen (may not detect synthetics)",
            "  - ECG (QTc prolongation with methadone)"
        ],
        "treatments": [
            "AIRWAY AND BREATHING (first priority):",
            "  - Position airway (jaw thrust, head tilt-chin lift)",
            "  - Bag-valve-mask ventilation",
            "  - Supplemental oxygen",
            "  - Intubation if severe and no response to naloxone",
            "",
            "NALOXONE (opioid antagonist):",
            "  - IV/IM/SC: 0.4-2mg, repeat every 2-3 minutes as needed",
            "  - Intranasal: 4mg spray in one nostril, may repeat",
            "  - Max dose: no ceiling, titrate to respiratory improvement",
            "  - Start with lower dose (0.04mg) if opioid-dependent to avoid withdrawal",
            "",
            "CONSIDERATIONS:",
            "  - Response within 1-2 minutes suggests opioid overdose",
            "  - Duration of naloxone (30-90 min) may be shorter than opioid",
            "  - Observe for recurrence (especially with long-acting opioids)",
            "  - May need continuous naloxone infusion",
            "",
            "POST-RESUSCITATION:",
            "  - Monitor for at least 4-6 hours (longer for long-acting opioids)",
            "  - Assess for complications (aspiration pneumonia, rhabdomyolysis)",
            "  - Offer addiction treatment/referral",
            "  - Prescribe take-home naloxone"
        ],
        "prevention": [
            "naloxone distribution programs",
            "opioid prescribing guidelines",
            "medication-assisted treatment (buprenorphine, methadone)",
            "supervised injection sites (where legal)",
            "fentanyl test strips"
        ],
        "source": "SAMHSA Opioid Overdose Prevention Toolkit; AHA/ACLS Guidelines",
        "citations": [
            "Substance Abuse and Mental Health Services Administration. SAMHSA Opioid Overdose Prevention Toolkit. 2018.",
            "Schiller EY, et al. Opioid Overdose. StatPearls. 2024.",
            "Centers for Disease Control and Prevention. Drug Overdose Deaths in the United States, 2001-2021. NCHS Data Brief. 2022."
        ],
        "text": "Disease: Opioid Overdose | Description: Life-threatening emergency with respiratory depression, altered mental status, miosis. >80,000 deaths annually in US. Can occur with prescription opioids, heroin, or fentanyl. Naloxone reverses effects within minutes. | Classic triad: respiratory depression (RR<12), altered mental status, pinpoint pupils | Symptoms: slow shallow breathing, coma, cyanosis, bradycardia, hypotension | Diagnostics: Clinical diagnosis - don't delay treatment. Check glucose, pulse ox. | Treatments: Airway management, bag-mask ventilation, naloxone IV/IM 0.4-2mg q2-3min or intranasal 4mg. Start low if opioid-dependent. Observe 4-6h. Offer addiction treatment, prescribe take-home naloxone | Source: SAMHSA Opioid Overdose Prevention Toolkit"
    })
    
    return entries


def append_to_jsonl():
    """Append new medical entries to the existing JSONL file."""
    entries = create_additional_medical_entries()
    
    print(f"Adding {len(entries)} additional comprehensive medical knowledge entries...")
    
    with open(DATA_FILE, 'a', encoding='utf-8') as f:
        for entry in entries:
            f.write(json.dumps(entry, ensure_ascii=False) + '\n')
    
    print(f"✅ Successfully added {len(entries)} detailed medical entries to {DATA_FILE}")
    print("\nEntries added:")
    for entry in entries:
        print(f"  - {entry['name']}")


if __name__ == "__main__":
    append_to_jsonl()
