#!/usr/bin/env python3
"""
Synthea to MariaDB Loader
=========================
Loads Synthea-generated synthetic patient data from CSV files into MariaDB.

This script reads the CSV files generated by Synthea and populates the
healthcare database with realistic patient data including:
- Patients (demographics + AI model features)
- Conditions (diagnoses/medical history)
- Encounters (appointments/visits)
- Medications (prescriptions)
- Allergies
- Observations (lab results, vitals)
- Procedures
- AI Risk Assessments (cardiovascular, diabetes)

AI Model Integration:
- Cardiovascular: age, gender, height, weight, bp_systolic, bp_diastolic, 
                  cholesterol, glucose, smoking, alcohol, physical_activity
- Diabetes: age, gender, hypertension, heart_disease, smoking_history, 
            bmi, hba1c, blood_glucose

Usage:
    python synthea_to_mariadb.py [--synthea-dir ./synthea_output/csv] [--clear]
"""

import mariadb
import os
import csv
import argparse
import random
from dotenv import load_dotenv
from datetime import datetime, date
import uuid

# Load environment variables
load_dotenv()

# Database configuration
DB_HOST = os.getenv('DB_HOST')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME = os.getenv('DB_NAME')
DB_PORT = int(os.getenv('DB_PORT', 3305))

# Default Synthea output directory
DEFAULT_SYNTHEA_DIR = os.path.join(os.path.dirname(__file__), 'synthea_output', 'csv')


def get_db_connection():
    """Establish database connection"""
    return mariadb.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME,
        port=DB_PORT
    )


def execute_query(query, params=None, return_lastrowid=True):
    """Execute a database query"""
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        if params:
            cursor.execute(query, params)
        else:
            cursor.execute(query)

        if query.strip().upper().startswith('INSERT'):
            conn.commit()
            return cursor.lastrowid if return_lastrowid else cursor.rowcount
        elif query.strip().upper().startswith(('UPDATE', 'DELETE', 'CREATE', 'ALTER', 'DROP', 'TRUNCATE')):
            conn.commit()
            return cursor.rowcount
        else:
            columns = [desc[0] for desc in cursor.description] if cursor.description else []
            rows = cursor.fetchall()
            return [dict(zip(columns, row)) for row in rows]

    except mariadb.Error as e:
        print(f"Database error: {e}")
        return None
    finally:
        if conn:
            conn.close()


def execute_many(query, params_list):
    """Execute query with multiple parameter sets"""
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.executemany(query, params_list)
        conn.commit()
        return cursor.rowcount
    except mariadb.Error as e:
        print(f"Database error: {e}")
        return None
    finally:
        if conn:
            conn.close()


def read_csv_file(filepath):
    """Read a CSV file and return list of dictionaries"""
    if not os.path.exists(filepath):
        print(f"⚠️  File not found: {filepath}")
        return []
    
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        return list(reader)


def parse_date(date_str):
    """Parse various date formats from Synthea"""
    if not date_str or date_str == '':
        return None
    
    # Try different formats
    formats = [
        '%Y-%m-%dT%H:%M:%SZ',
        '%Y-%m-%d',
        '%Y-%m-%dT%H:%M:%S',
    ]
    
    for fmt in formats:
        try:
            return datetime.strptime(date_str, fmt).date()
        except ValueError:
            continue
    
    return None


def parse_datetime(datetime_str):
    """Parse datetime from Synthea"""
    if not datetime_str or datetime_str == '':
        return None
    
    formats = [
        '%Y-%m-%dT%H:%M:%SZ',
        '%Y-%m-%dT%H:%M:%S',
        '%Y-%m-%d',
    ]
    
    for fmt in formats:
        try:
            return datetime.strptime(datetime_str, fmt)
        except ValueError:
            continue
    
    return None


def create_synthea_tables():
    """Create tables optimized for Synthea data"""
    
    tables_sql = """
    -- Synthea Patient table (with UUID support)
    CREATE TABLE IF NOT EXISTS Synthea_Patient (
        patient_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100) UNIQUE NOT NULL,
        first_name VARCHAR(100),
        middle_name VARCHAR(100),
        last_name VARCHAR(100),
        prefix VARCHAR(20),
        suffix VARCHAR(20),
        maiden_name VARCHAR(100),
        marital_status VARCHAR(20),
        race VARCHAR(50),
        ethnicity VARCHAR(50),
        gender ENUM('M', 'F', 'Other'),
        birthdate DATE,
        deathdate DATE,
        ssn VARCHAR(20),
        drivers_license VARCHAR(50),
        passport VARCHAR(50),
        address TEXT,
        city VARCHAR(100),
        state VARCHAR(100),
        county VARCHAR(100),
        zip VARCHAR(20),
        latitude DECIMAL(10, 8),
        longitude DECIMAL(11, 8),
        healthcare_expenses DECIMAL(12, 2),
        healthcare_coverage DECIMAL(12, 2),
        income INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_synthea_id (synthea_id),
        INDEX idx_name (last_name, first_name)
    );

    -- Synthea Condition table (diagnoses)
    CREATE TABLE IF NOT EXISTS Synthea_Condition (
        condition_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        code VARCHAR(50),
        code_system VARCHAR(100),
        description TEXT,
        start_date DATE,
        stop_date DATE,
        is_active TINYINT DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Encounter table (visits/appointments)
    CREATE TABLE IF NOT EXISTS Synthea_Encounter (
        encounter_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100) UNIQUE NOT NULL,
        synthea_patient_id VARCHAR(100),
        synthea_organization_id VARCHAR(100),
        synthea_provider_id VARCHAR(100),
        synthea_payer_id VARCHAR(100),
        encounter_class VARCHAR(50),
        code VARCHAR(50),
        description TEXT,
        start_datetime DATETIME,
        stop_datetime DATETIME,
        base_cost DECIMAL(10, 2),
        total_claim_cost DECIMAL(10, 2),
        payer_coverage DECIMAL(10, 2),
        reason_code VARCHAR(50),
        reason_description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_synthea_id (synthea_id),
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_date (start_datetime),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Medication table
    CREATE TABLE IF NOT EXISTS Synthea_Medication (
        medication_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        synthea_payer_id VARCHAR(100),
        code VARCHAR(50),
        description TEXT,
        start_datetime DATETIME,
        stop_datetime DATETIME,
        base_cost DECIMAL(10, 2),
        payer_coverage DECIMAL(10, 2),
        dispenses INT,
        total_cost DECIMAL(10, 2),
        reason_code VARCHAR(50),
        reason_description TEXT,
        is_active TINYINT DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Allergy table
    CREATE TABLE IF NOT EXISTS Synthea_Allergy (
        allergy_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        code VARCHAR(50),
        code_system VARCHAR(50),
        description TEXT,
        allergy_type VARCHAR(50),
        category VARCHAR(50),
        reaction1_code VARCHAR(50),
        reaction1_description TEXT,
        reaction1_severity VARCHAR(20),
        reaction2_code VARCHAR(50),
        reaction2_description TEXT,
        reaction2_severity VARCHAR(20),
        start_date DATE,
        stop_date DATE,
        is_active TINYINT DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Observation table (labs, vitals)
    CREATE TABLE IF NOT EXISTS Synthea_Observation (
        observation_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        observation_date DATETIME,
        category VARCHAR(50),
        code VARCHAR(50),
        description TEXT,
        value TEXT,
        units VARCHAR(50),
        value_type VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        INDEX idx_date (observation_date),
        INDEX idx_category (category),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Procedure table
    CREATE TABLE IF NOT EXISTS Synthea_Procedure (
        procedure_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        code VARCHAR(50),
        code_system VARCHAR(100),
        description TEXT,
        start_datetime DATETIME,
        stop_datetime DATETIME,
        base_cost DECIMAL(10, 2),
        reason_code VARCHAR(50),
        reason_description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        INDEX idx_date (start_datetime),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Organization table (healthcare facilities)
    CREATE TABLE IF NOT EXISTS Synthea_Organization (
        organization_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100) UNIQUE NOT NULL,
        name VARCHAR(200),
        address TEXT,
        city VARCHAR(100),
        state VARCHAR(100),
        zip VARCHAR(20),
        latitude DECIMAL(10, 8),
        longitude DECIMAL(11, 8),
        phone VARCHAR(50),
        revenue DECIMAL(15, 2),
        utilization INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_synthea_id (synthea_id)
    );

    -- Synthea Provider table (doctors/clinicians)
    CREATE TABLE IF NOT EXISTS Synthea_Provider (
        provider_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100) UNIQUE NOT NULL,
        synthea_organization_id VARCHAR(100),
        name VARCHAR(200),
        gender ENUM('M', 'F', 'Other'),
        speciality VARCHAR(200),
        address TEXT,
        city VARCHAR(100),
        state VARCHAR(100),
        zip VARCHAR(20),
        latitude DECIMAL(10, 8),
        longitude DECIMAL(11, 8),
        utilization INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_synthea_id (synthea_id),
        INDEX idx_organization (synthea_organization_id)
    );

    -- Synthea Care Plan table
    CREATE TABLE IF NOT EXISTS Synthea_CarePlan (
        careplan_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100),
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        code VARCHAR(50),
        description TEXT,
        start_date DATE,
        stop_date DATE,
        reason_code VARCHAR(50),
        reason_description TEXT,
        is_active TINYINT DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Immunization table
    CREATE TABLE IF NOT EXISTS Synthea_Immunization (
        immunization_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        immunization_date DATE,
        code VARCHAR(50),
        description TEXT,
        base_cost DECIMAL(10, 2),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_code (code),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Device table
    CREATE TABLE IF NOT EXISTS Synthea_Device (
        device_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        code VARCHAR(50),
        description TEXT,
        start_datetime DATETIME,
        stop_datetime DATETIME,
        udi VARCHAR(200),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Synthea Imaging Study table
    CREATE TABLE IF NOT EXISTS Synthea_ImagingStudy (
        imaging_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_id VARCHAR(100),
        synthea_patient_id VARCHAR(100),
        synthea_encounter_id VARCHAR(100),
        series_uid VARCHAR(200),
        study_date DATETIME,
        bodysite_code VARCHAR(50),
        bodysite_description TEXT,
        modality_code VARCHAR(20),
        modality_description TEXT,
        instance_uid VARCHAR(200),
        sop_code VARCHAR(50),
        sop_description TEXT,
        procedure_code VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Patient AI Features table (for ML model inputs)
    CREATE TABLE IF NOT EXISTS Patient_AI_Features (
        feature_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100) UNIQUE,
        -- Demographics
        age_years DECIMAL(5, 2),
        gender_numeric INT COMMENT '0=Male, 1=Female, 2=Other',
        -- Physical measurements
        height_cm DECIMAL(5, 1),
        weight_kg DECIMAL(5, 1),
        bmi DECIMAL(5, 2),
        -- Cardiovascular metrics
        bp_systolic INT COMMENT 'Systolic blood pressure (ap_hi)',
        bp_diastolic INT COMMENT 'Diastolic blood pressure (ap_lo)',
        cholesterol_level INT COMMENT '1=normal, 2=above normal, 3=well above normal',
        glucose_level INT COMMENT '1=normal, 2=above normal, 3=well above normal',
        -- Lifestyle factors
        is_smoker INT DEFAULT 0 COMMENT '0=no, 1=yes',
        smoking_history VARCHAR(50) COMMENT 'never, former, current, etc.',
        alcohol_use INT DEFAULT 0 COMMENT '0=no, 1=yes',
        physical_activity INT DEFAULT 1 COMMENT '0=inactive, 1=active',
        -- Diabetes-specific
        has_hypertension INT DEFAULT 0,
        has_heart_disease INT DEFAULT 0,
        hba1c_level DECIMAL(4, 2) COMMENT 'Glycated hemoglobin %',
        blood_glucose_fasting INT COMMENT 'Fasting blood glucose mg/dL',
        -- Risk scores (calculated)
        cardio_risk_score DECIMAL(5, 4),
        cardio_risk_category VARCHAR(20),
        diabetes_risk_score DECIMAL(5, 4),
        diabetes_risk_category VARCHAR(20),
        -- Metadata
        last_observation_date DATE,
        data_completeness_score DECIMAL(3, 2) COMMENT 'Percentage of features available',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_cardio_risk (cardio_risk_category),
        INDEX idx_diabetes_risk (diabetes_risk_category),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- AI Risk Assessment History table
    CREATE TABLE IF NOT EXISTS AI_Risk_Assessment (
        assessment_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        assessment_type ENUM('cardiovascular', 'diabetes', 'general') NOT NULL,
        risk_score DECIMAL(5, 4),
        risk_category VARCHAR(20),
        confidence_score DECIMAL(5, 4),
        -- Input features snapshot (JSON)
        input_features JSON,
        -- Explanation
        top_risk_factors JSON COMMENT 'Top factors contributing to risk',
        recommendations JSON COMMENT 'AI-generated recommendations',
        -- Metadata
        model_version VARCHAR(50),
        assessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        assessed_by VARCHAR(100) DEFAULT 'AI_Model',
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_type (assessment_type),
        INDEX idx_date (assessed_at),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );

    -- Vital Signs Summary table (aggregated from observations)
    CREATE TABLE IF NOT EXISTS Patient_Vitals_Summary (
        vitals_id INT AUTO_INCREMENT PRIMARY KEY,
        synthea_patient_id VARCHAR(100),
        observation_date DATE,
        -- Vitals
        height_cm DECIMAL(5, 1),
        weight_kg DECIMAL(5, 1),
        bmi DECIMAL(5, 2),
        bp_systolic INT,
        bp_diastolic INT,
        heart_rate INT,
        respiratory_rate INT,
        body_temperature DECIMAL(4, 1),
        oxygen_saturation DECIMAL(5, 2),
        -- Lab values
        total_cholesterol DECIMAL(5, 1),
        ldl_cholesterol DECIMAL(5, 1),
        hdl_cholesterol DECIMAL(5, 1),
        triglycerides DECIMAL(6, 1),
        blood_glucose DECIMAL(5, 1),
        hba1c DECIMAL(4, 2),
        creatinine DECIMAL(4, 2),
        egfr DECIMAL(5, 1),
        -- Metadata
        encounter_id VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_patient (synthea_patient_id),
        INDEX idx_date (observation_date),
        FOREIGN KEY (synthea_patient_id) REFERENCES Synthea_Patient(synthea_id) ON DELETE CASCADE
    );
    """
    
    # Execute each table creation
    for table_sql in tables_sql.split(';'):
        if table_sql.strip():
            execute_query(table_sql.strip())
    
    print("✅ Synthea tables created/verified")


def clear_synthea_tables():
    """Clear all Synthea tables"""
    tables = [
        'AI_Risk_Assessment', 'Patient_Vitals_Summary', 'Patient_AI_Features',
        'Synthea_ImagingStudy', 'Synthea_Device', 'Synthea_Immunization',
        'Synthea_CarePlan', 'Synthea_Procedure', 'Synthea_Observation',
        'Synthea_Allergy', 'Synthea_Medication', 'Synthea_Encounter',
        'Synthea_Condition', 'Synthea_Provider', 'Synthea_Organization',
        'Synthea_Patient'
    ]
    
    for table in tables:
        execute_query(f"TRUNCATE TABLE {table}")
    
    print("🗑️  Synthea tables cleared")


def load_patients(synthea_dir):
    """Load patients from Synthea CSV"""
    print("\n👤 Loading Patients...")
    
    filepath = os.path.join(synthea_dir, 'patients.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Patient (
        synthea_id, first_name, middle_name, last_name, prefix, suffix,
        maiden_name, marital_status, race, ethnicity, gender, birthdate,
        deathdate, ssn, drivers_license, passport, address, city, state,
        county, zip, latitude, longitude, healthcare_expenses,
        healthcare_coverage, income
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE
        first_name = VALUES(first_name),
        last_name = VALUES(last_name),
        updated_at = CURRENT_TIMESTAMP
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('Id', ''),
            r.get('FIRST', ''),
            r.get('MIDDLE', ''),
            r.get('LAST', ''),
            r.get('PREFIX', ''),
            r.get('SUFFIX', ''),
            r.get('MAIDEN', ''),
            r.get('MARITAL', ''),
            r.get('RACE', ''),
            r.get('ETHNICITY', ''),
            r.get('GENDER', ''),
            parse_date(r.get('BIRTHDATE')),
            parse_date(r.get('DEATHDATE')),
            r.get('SSN', ''),
            r.get('DRIVERS', ''),
            r.get('PASSPORT', ''),
            r.get('ADDRESS', ''),
            r.get('CITY', ''),
            r.get('STATE', ''),
            r.get('COUNTY', ''),
            r.get('ZIP', ''),
            float(r.get('LAT', 0) or 0),
            float(r.get('LON', 0) or 0),
            float(r.get('HEALTHCARE_EXPENSES', 0) or 0),
            float(r.get('HEALTHCARE_COVERAGE', 0) or 0),
            int(float(r.get('INCOME', 0) or 0))
        ))
    
    count = execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} patients")
    return records


def load_organizations(synthea_dir):
    """Load organizations from Synthea CSV"""
    print("\n🏥 Loading Organizations...")
    
    filepath = os.path.join(synthea_dir, 'organizations.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Organization (
        synthea_id, name, address, city, state, zip,
        latitude, longitude, phone, revenue, utilization
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE name = VALUES(name)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('Id', ''),
            r.get('NAME', ''),
            r.get('ADDRESS', ''),
            r.get('CITY', ''),
            r.get('STATE', ''),
            r.get('ZIP', ''),
            float(r.get('LAT', 0) or 0),
            float(r.get('LON', 0) or 0),
            r.get('PHONE', ''),
            float(r.get('REVENUE', 0) or 0),
            int(float(r.get('UTILIZATION', 0) or 0))
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} organizations")
    return records


def load_providers(synthea_dir):
    """Load providers from Synthea CSV"""
    print("\n👨‍⚕️ Loading Providers...")
    
    filepath = os.path.join(synthea_dir, 'providers.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Provider (
        synthea_id, synthea_organization_id, name, gender, speciality,
        address, city, state, zip, latitude, longitude, utilization
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE name = VALUES(name)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('Id', ''),
            r.get('ORGANIZATION', ''),
            r.get('NAME', ''),
            r.get('GENDER', ''),
            r.get('SPECIALITY', ''),
            r.get('ADDRESS', ''),
            r.get('CITY', ''),
            r.get('STATE', ''),
            r.get('ZIP', ''),
            float(r.get('LAT', 0) or 0),
            float(r.get('LON', 0) or 0),
            int(float(r.get('UTILIZATION', 0) or 0))
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} providers")
    return records


def load_encounters(synthea_dir):
    """Load encounters from Synthea CSV"""
    print("\n📅 Loading Encounters...")
    
    filepath = os.path.join(synthea_dir, 'encounters.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Encounter (
        synthea_id, synthea_patient_id, synthea_organization_id,
        synthea_provider_id, synthea_payer_id, encounter_class, code,
        description, start_datetime, stop_datetime, base_cost,
        total_claim_cost, payer_coverage, reason_code, reason_description
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE description = VALUES(description)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('Id', ''),
            r.get('PATIENT', ''),
            r.get('ORGANIZATION', ''),
            r.get('PROVIDER', ''),
            r.get('PAYER', ''),
            r.get('ENCOUNTERCLASS', ''),
            r.get('CODE', ''),
            r.get('DESCRIPTION', ''),
            parse_datetime(r.get('START')),
            parse_datetime(r.get('STOP')),
            float(r.get('BASE_ENCOUNTER_COST', 0) or 0),
            float(r.get('TOTAL_CLAIM_COST', 0) or 0),
            float(r.get('PAYER_COVERAGE', 0) or 0),
            r.get('REASONCODE', ''),
            r.get('REASONDESCRIPTION', '')
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} encounters")
    return records


def load_conditions(synthea_dir):
    """Load conditions from Synthea CSV"""
    print("\n🩺 Loading Conditions...")
    
    filepath = os.path.join(synthea_dir, 'conditions.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Condition (
        synthea_patient_id, synthea_encounter_id, code, code_system,
        description, start_date, stop_date, is_active
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        stop_date = parse_date(r.get('STOP'))
        is_active = 1 if not stop_date else 0
        
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('CODE', ''),
            r.get('SYSTEM', ''),
            r.get('DESCRIPTION', ''),
            parse_date(r.get('START')),
            stop_date,
            is_active
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} conditions")
    return records


def load_medications(synthea_dir):
    """Load medications from Synthea CSV"""
    print("\n💊 Loading Medications...")
    
    filepath = os.path.join(synthea_dir, 'medications.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Medication (
        synthea_patient_id, synthea_encounter_id, synthea_payer_id, code,
        description, start_datetime, stop_datetime, base_cost, payer_coverage,
        dispenses, total_cost, reason_code, reason_description, is_active
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        stop_datetime = parse_datetime(r.get('STOP'))
        is_active = 1 if not stop_datetime else 0
        
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('PAYER', ''),
            r.get('CODE', ''),
            r.get('DESCRIPTION', ''),
            parse_datetime(r.get('START')),
            stop_datetime,
            float(r.get('BASE_COST', 0) or 0),
            float(r.get('PAYER_COVERAGE', 0) or 0),
            int(float(r.get('DISPENSES', 0) or 0)),
            float(r.get('TOTALCOST', 0) or 0),
            r.get('REASONCODE', ''),
            r.get('REASONDESCRIPTION', ''),
            is_active
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} medications")
    return records


def load_allergies(synthea_dir):
    """Load allergies from Synthea CSV"""
    print("\n🤧 Loading Allergies...")
    
    filepath = os.path.join(synthea_dir, 'allergies.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Allergy (
        synthea_patient_id, synthea_encounter_id, code, code_system,
        description, allergy_type, category, reaction1_code, reaction1_description,
        reaction1_severity, reaction2_code, reaction2_description, reaction2_severity,
        start_date, stop_date, is_active
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        stop_date = parse_date(r.get('STOP'))
        is_active = 1 if not stop_date else 0
        
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('CODE', ''),
            r.get('SYSTEM', ''),
            r.get('DESCRIPTION', ''),
            r.get('TYPE', ''),
            r.get('CATEGORY', ''),
            r.get('REACTION1', ''),
            r.get('DESCRIPTION1', ''),
            r.get('SEVERITY1', ''),
            r.get('REACTION2', ''),
            r.get('DESCRIPTION2', ''),
            r.get('SEVERITY2', ''),
            parse_date(r.get('START')),
            stop_date,
            is_active
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} allergies")
    return records


def load_observations(synthea_dir):
    """Load observations from Synthea CSV"""
    print("\n📊 Loading Observations (this may take a while)...")
    
    filepath = os.path.join(synthea_dir, 'observations.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Observation (
        synthea_patient_id, synthea_encounter_id, observation_date,
        category, code, description, value, units, value_type
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    # Process in batches for large datasets
    batch_size = 1000
    total_loaded = 0
    
    for i in range(0, len(records), batch_size):
        batch = records[i:i+batch_size]
        params_list = []
        
        for r in batch:
            params_list.append((
                r.get('PATIENT', ''),
                r.get('ENCOUNTER', ''),
                parse_datetime(r.get('DATE')),
                r.get('CATEGORY', ''),
                r.get('CODE', ''),
                r.get('DESCRIPTION', ''),
                r.get('VALUE', ''),
                r.get('UNITS', ''),
                r.get('TYPE', '')
            ))
        
        execute_many(query, params_list)
        total_loaded += len(batch)
        print(f"   ... {total_loaded}/{len(records)} observations loaded", end='\r')
    
    print(f"\n   ✓ Loaded {len(records)} observations")
    return records


def load_procedures(synthea_dir):
    """Load procedures from Synthea CSV"""
    print("\n🔧 Loading Procedures...")
    
    filepath = os.path.join(synthea_dir, 'procedures.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Procedure (
        synthea_patient_id, synthea_encounter_id, code, code_system,
        description, start_datetime, stop_datetime, base_cost,
        reason_code, reason_description
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('CODE', ''),
            r.get('SYSTEM', ''),
            r.get('DESCRIPTION', ''),
            parse_datetime(r.get('START')),
            parse_datetime(r.get('STOP')),
            float(r.get('BASE_COST', 0) or 0),
            r.get('REASONCODE', ''),
            r.get('REASONDESCRIPTION', '')
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} procedures")
    return records


def load_careplans(synthea_dir):
    """Load care plans from Synthea CSV"""
    print("\n📋 Loading Care Plans...")
    
    filepath = os.path.join(synthea_dir, 'careplans.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_CarePlan (
        synthea_id, synthea_patient_id, synthea_encounter_id, code,
        description, start_date, stop_date, reason_code, reason_description, is_active
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        stop_date = parse_date(r.get('STOP'))
        is_active = 1 if not stop_date else 0
        
        params_list.append((
            r.get('Id', ''),
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('CODE', ''),
            r.get('DESCRIPTION', ''),
            parse_date(r.get('START')),
            stop_date,
            r.get('REASONCODE', ''),
            r.get('REASONDESCRIPTION', ''),
            is_active
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} care plans")
    return records


def load_immunizations(synthea_dir):
    """Load immunizations from Synthea CSV"""
    print("\n💉 Loading Immunizations...")
    
    filepath = os.path.join(synthea_dir, 'immunizations.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Immunization (
        synthea_patient_id, synthea_encounter_id, immunization_date,
        code, description, base_cost
    ) VALUES (?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            parse_date(r.get('DATE')),
            r.get('CODE', ''),
            r.get('DESCRIPTION', ''),
            float(r.get('BASE_COST', 0) or 0)
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} immunizations")
    return records


def load_devices(synthea_dir):
    """Load devices from Synthea CSV"""
    print("\n🔌 Loading Devices...")
    
    filepath = os.path.join(synthea_dir, 'devices.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_Device (
        synthea_patient_id, synthea_encounter_id, code, description,
        start_datetime, stop_datetime, udi
    ) VALUES (?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('CODE', ''),
            r.get('DESCRIPTION', ''),
            parse_datetime(r.get('START')),
            parse_datetime(r.get('STOP')),
            r.get('UDI', '')
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} devices")
    return records


def load_imaging_studies(synthea_dir):
    """Load imaging studies from Synthea CSV"""
    print("\n🔬 Loading Imaging Studies...")
    
    filepath = os.path.join(synthea_dir, 'imaging_studies.csv')
    records = read_csv_file(filepath)
    
    if not records:
        return []
    
    query = """
    INSERT INTO Synthea_ImagingStudy (
        synthea_id, synthea_patient_id, synthea_encounter_id, series_uid,
        study_date, bodysite_code, bodysite_description, modality_code,
        modality_description, instance_uid, sop_code, sop_description, procedure_code
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    params_list = []
    for r in records:
        params_list.append((
            r.get('Id', ''),
            r.get('PATIENT', ''),
            r.get('ENCOUNTER', ''),
            r.get('SERIES_UID', ''),
            parse_datetime(r.get('DATE')),
            r.get('BODYSITE_CODE', ''),
            r.get('BODYSITE_DESCRIPTION', ''),
            r.get('MODALITY_CODE', ''),
            r.get('MODALITY_DESCRIPTION', ''),
            r.get('INSTANCE_UID', ''),
            r.get('SOP_CODE', ''),
            r.get('SOP_DESCRIPTION', ''),
            r.get('PROCEDURE_CODE', '')
        ))
    
    execute_many(query, params_list)
    print(f"   ✓ Loaded {len(records)} imaging studies")
    return records


# =============================================================================
# AI FEATURE EXTRACTION
# =============================================================================
# LOINC codes for common observations used by AI models
LOINC_CODES = {
    'height': '8302-2',           # Body height
    'weight': '29463-7',          # Body weight
    'bmi': '39156-5',             # BMI
    'bp_systolic': '8480-6',      # Systolic blood pressure
    'bp_diastolic': '8462-4',     # Diastolic blood pressure
    'heart_rate': '8867-4',       # Heart rate
    'respiratory_rate': '9279-1', # Respiratory rate
    'glucose': '2339-0',          # Glucose [Mass/volume] in Blood
    'glucose_fasting': '1558-6',  # Fasting glucose
    'hba1c': '4548-4',            # Hemoglobin A1c
    'cholesterol_total': '2093-3',# Total cholesterol
    'hdl': '2085-9',              # HDL cholesterol
    'ldl': '2089-1',              # LDL cholesterol
    'triglycerides': '2571-8',    # Triglycerides
}

# SNOMED codes for conditions relevant to AI models
SNOMED_CONDITIONS = {
    'hypertension': ['38341003', '59621000'],  # Hypertension, essential hypertension
    'diabetes': ['44054006', '73211009'],       # Type 2 diabetes, diabetes mellitus
    'heart_disease': ['49601007', '22298006', '53741008', '399211009'],  # Heart diseases
    'obesity': ['162864005', '408512008'],      # BMI >30
}


def extract_patient_ai_features():
    """
    Extract AI model features from Synthea observations and conditions.
    Populates the Patient_AI_Features table with data needed for cardiovascular and diabetes models.
    Bulk loads all data first, processes in parallel using all cores, then bulk writes.
    """
    import concurrent.futures
    import multiprocessing
    import time
    from datetime import date
    from collections import defaultdict
    
    print("\n" + "=" * 60)
    print("🤖 Extracting AI Model Features (Bulk Load + Parallel Process)")
    print("=" * 60)
    
    num_cores = multiprocessing.cpu_count()
    print(f"🖥️  Detected {num_cores} CPU cores - will use all for in-memory processing")
    
    start_time = time.time()
    
    # ========== PHASE 1: BULK LOAD ALL DATA (Single Connection) ==========
    print("\n📥 Phase 1: Bulk loading all data from MariaDB...")
    phase1_start = time.time()
    
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    
    # Load all patients
    print("   Loading patients...", end=" ", flush=True)
    cursor.execute("SELECT synthea_id, first_name, last_name, birthdate, gender FROM Synthea_Patient")
    patients = {p['synthea_id']: p for p in cursor.fetchall()}
    print(f"✅ {len(patients)} patients")
    
    # Load all observations (indexed by patient)
    print("   Loading observations...", end=" ", flush=True)
    cursor.execute("""
        SELECT synthea_patient_id, code, value, observation_date, description
        FROM Synthea_Observation 
        WHERE value IS NOT NULL
        ORDER BY synthea_patient_id, code, observation_date DESC
    """)
    observations_by_patient = defaultdict(lambda: defaultdict(list))
    obs_count = 0
    for obs in cursor.fetchall():
        observations_by_patient[obs['synthea_patient_id']][obs['code']].append(obs)
        obs_count += 1
    print(f"✅ {obs_count} observations")
    
    # Load all conditions (indexed by patient)
    print("   Loading conditions...", end=" ", flush=True)
    cursor.execute("""
        SELECT synthea_patient_id, code, description
        FROM Synthea_Condition
    """)
    conditions_by_patient = defaultdict(list)
    cond_count = 0
    for cond in cursor.fetchall():
        conditions_by_patient[cond['synthea_patient_id']].append(cond)
        cond_count += 1
    print(f"✅ {cond_count} conditions")
    
    cursor.close()
    conn.close()
    
    phase1_time = time.time() - phase1_start
    print(f"   ⏱️  Phase 1 completed in {phase1_time:.2f}s")
    
    # ========== PHASE 2: PARALLEL IN-MEMORY PROCESSING ==========
    print(f"\n⚡ Phase 2: Parallel processing with {num_cores} cores...")
    phase2_start = time.time()
    
    today = date.today()
    
    def process_patient(patient_id):
        """Process a single patient entirely in memory"""
        patient = patients[patient_id]
        patient_obs = observations_by_patient[patient_id]
        patient_conds = conditions_by_patient[patient_id]
        
        result = {
            'synthea_id': patient_id,
            'name': f"{patient['first_name']} {patient['last_name']}",
            'observations_found': 0,
            'conditions_found': [],
            'data': None
        }
        
        # Calculate age
        age = None
        if patient['birthdate']:
            birth = patient['birthdate']
            age = today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))
        
        # Gender numeric
        gender = patient['gender']
        gender_numeric = 1 if gender and gender.upper() == 'F' else 2
        
        # Get latest observations
        observations = {}
        for obs_name, loinc_code in LOINC_CODES.items():
            obs_list = patient_obs.get(loinc_code, [])
            if obs_list:
                try:
                    observations[obs_name] = float(obs_list[0]['value'])
                    result['observations_found'] += 1
                except (ValueError, TypeError):
                    pass
        
        # BMI calculation
        height_cm = observations.get('height')
        weight_kg = observations.get('weight')
        bmi = observations.get('bmi')
        if not bmi and height_cm and weight_kg:
            height_m = height_cm / 100
            bmi = weight_kg / (height_m * height_m)
        
        # Check conditions
        has_hypertension = 0
        has_heart_disease = 0
        has_diabetes = 0
        
        cond_codes = {c['code'] for c in patient_conds}
        cond_descs = ' '.join([c['description'] or '' for c in patient_conds]).lower()
        
        for condition_type, snomed_codes in SNOMED_CONDITIONS.items():
            if any(code in cond_codes for code in snomed_codes):
                if condition_type == 'hypertension':
                    has_hypertension = 1
                    result['conditions_found'].append('HTN')
                elif condition_type == 'heart_disease':
                    has_heart_disease = 1
                    result['conditions_found'].append('HD')
                elif condition_type == 'diabetes':
                    has_diabetes = 1
                    result['conditions_found'].append('DM')
        
        # Smoking status from observations
        is_smoker = 0
        smoking_history = 'never'
        for code in ['72166-2', '266918002']:
            obs_list = patient_obs.get(code, [])
            if obs_list:
                val = (obs_list[0].get('value') or '').lower()
                desc = (obs_list[0].get('description') or '').lower()
                if 'current' in val or 'current' in desc or 'smoker' in val:
                    is_smoker = 1
                    smoking_history = 'current'
                elif 'former' in val or 'former' in desc:
                    smoking_history = 'former'
                break
        
        # Check smoking in all observations descriptions
        if smoking_history == 'never':
            for code, obs_list in patient_obs.items():
                for obs in obs_list:
                    desc = (obs.get('description') or '').lower()
                    val = (obs.get('value') or '').lower()
                    if 'smoking' in desc or 'tobacco' in desc:
                        if 'current' in val or 'current' in desc:
                            is_smoker = 1
                            smoking_history = 'current'
                        elif 'former' in val or 'former' in desc:
                            smoking_history = 'former'
                        break
                if smoking_history != 'never':
                    break
        
        # Alcohol
        alcohol_use = 1 if 'alcohol' in cond_descs else 0
        physical_activity = 1
        
        # Vitals
        bp_systolic = observations.get('bp_systolic')
        bp_diastolic = observations.get('bp_diastolic')
        glucose = observations.get('glucose') or observations.get('glucose_fasting')
        hba1c = observations.get('hba1c')
        cholesterol = observations.get('cholesterol_total')
        
        # Cholesterol level
        cholesterol_level = 1
        if cholesterol:
            if cholesterol >= 240:
                cholesterol_level = 3
            elif cholesterol >= 200:
                cholesterol_level = 2
        
        # Glucose level
        glucose_level = 1
        if glucose:
            if glucose >= 126:
                glucose_level = 3
            elif glucose >= 100:
                glucose_level = 2
        
        result['age'] = age
        result['bmi'] = bmi
        result['data'] = (
            patient_id, age, gender_numeric,
            height_cm, weight_kg, bmi,
            bp_systolic, bp_diastolic, cholesterol_level, glucose_level,
            is_smoker, alcohol_use, physical_activity,
            has_hypertension, has_heart_disease,
            smoking_history, hba1c, glucose
        )
        
        return result
    
    # Process all patients in parallel
    patient_ids = list(patients.keys())
    results = []
    
    print(f"\n{'#':<5} {'Patient Name':<30} {'Age':<5} {'BMI':<8} {'Obs':<5} {'Conditions':<15} {'Status'}")
    print("-" * 90)
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_cores) as executor:
        future_to_id = {executor.submit(process_patient, pid): pid for pid in patient_ids}
        
        completed = 0
        for future in concurrent.futures.as_completed(future_to_id):
            completed += 1
            result = future.result()
            results.append(result)
            
            conds = ','.join(result['conditions_found']) if result['conditions_found'] else '-'
            bmi_str = f"{result['bmi']:.1f}" if result['bmi'] else '-'
            age_str = str(result['age']) if result['age'] else '-'
            
            print(f"{completed:<5} {result['name']:<30} {age_str:<5} {bmi_str:<8} {result['observations_found']:<5} {conds:<15} ✅")
            
            if completed % 25 == 0:
                elapsed = time.time() - phase2_start
                rate = completed / elapsed
                eta = (len(patient_ids) - completed) / rate if rate > 0 else 0
                print(f"   📊 Progress: {completed}/{len(patient_ids)} | {rate:.1f}/sec | ETA: {eta:.1f}s")
    
    phase2_time = time.time() - phase2_start
    print(f"\n   ⏱️  Phase 2 completed in {phase2_time:.2f}s")
    
    # ========== PHASE 3: BULK WRITE TO DATABASE ==========
    print("\n💾 Phase 3: Bulk writing to database...")
    phase3_start = time.time()
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    insert_sql = """
        INSERT INTO Patient_AI_Features (
            synthea_patient_id, age_years, gender_numeric,
            height_cm, weight_kg, bmi,
            bp_systolic, bp_diastolic, cholesterol_level, glucose_level,
            is_smoker, alcohol_use, physical_activity,
            has_hypertension, has_heart_disease,
            smoking_history, hba1c_level, blood_glucose_fasting
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            age_years = VALUES(age_years), gender_numeric = VALUES(gender_numeric),
            height_cm = VALUES(height_cm), weight_kg = VALUES(weight_kg), bmi = VALUES(bmi),
            bp_systolic = VALUES(bp_systolic), bp_diastolic = VALUES(bp_diastolic),
            cholesterol_level = VALUES(cholesterol_level), glucose_level = VALUES(glucose_level),
            is_smoker = VALUES(is_smoker), alcohol_use = VALUES(alcohol_use),
            physical_activity = VALUES(physical_activity), has_hypertension = VALUES(has_hypertension),
            has_heart_disease = VALUES(has_heart_disease), smoking_history = VALUES(smoking_history),
            hba1c_level = VALUES(hba1c_level), blood_glucose_fasting = VALUES(blood_glucose_fasting)
    """
    
    batch_data = [r['data'] for r in results if r['data']]
    cursor.executemany(insert_sql, batch_data)
    conn.commit()
    
    cursor.close()
    conn.close()
    
    phase3_time = time.time() - phase3_start
    print(f"   ⏱️  Phase 3 completed in {phase3_time:.2f}s")
    
    # ========== SUMMARY ==========
    total_time = time.time() - start_time
    print("\n" + "=" * 60)
    print(f"✅ AI Feature Extraction Complete!")
    print(f"   Total patients: {len(results)}")
    print(f"   Total time: {total_time:.2f}s ({total_time/60:.2f} min)")
    print(f"   Rate: {len(results)/total_time:.1f} patients/sec")
    print("=" * 60)
    
    return len(results)


def populate_vitals_summary():
    """
    Populate the Patient_Vitals_Summary table with aggregated vital statistics.
    Bulk loads all observations, processes in parallel, bulk writes results.
    """
    import concurrent.futures
    import multiprocessing
    import time
    from collections import defaultdict
    import re
    
    print("\n" + "=" * 60)
    print("📈 Populating Vitals Summary (Bulk Load + Parallel Process)")
    print("=" * 60)
    
    num_cores = multiprocessing.cpu_count()
    print(f"🖥️  Detected {num_cores} CPU cores - will use all for in-memory processing")
    
    start_time = time.time()
    
    vital_codes = {
        'bp_systolic': '8480-6',
        'bp_diastolic': '8462-4',
        'heart_rate': '8867-4',
        'weight': '29463-7',
        'glucose': '2339-0',
    }
    vital_code_set = set(vital_codes.values())
    
    # ========== PHASE 1: BULK LOAD ==========
    print("\n📥 Phase 1: Bulk loading vitals data...")
    phase1_start = time.time()
    
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    
    # Load patients
    print("   Loading patients...", end=" ", flush=True)
    cursor.execute("SELECT synthea_id, first_name, last_name FROM Synthea_Patient")
    patients = {p['synthea_id']: p for p in cursor.fetchall()}
    print(f"✅ {len(patients)}")
    
    # Load only vitals observations
    print("   Loading vitals observations...", end=" ", flush=True)
    placeholders = ','.join(['%s'] * len(vital_code_set))
    cursor.execute(f"""
        SELECT synthea_patient_id, code, value, observation_date
        FROM Synthea_Observation 
        WHERE code IN ({placeholders}) AND value IS NOT NULL
    """, list(vital_code_set))
    
    obs_by_patient_code = defaultdict(lambda: defaultdict(list))
    obs_count = 0
    numeric_pattern = re.compile(r'^-?[0-9]+\.?[0-9]*$')
    
    for obs in cursor.fetchall():
        # Filter numeric values only
        if obs['value'] and numeric_pattern.match(str(obs['value'])):
            try:
                val = float(obs['value'])
                obs_by_patient_code[obs['synthea_patient_id']][obs['code']].append({
                    'value': val,
                    'date': obs['observation_date']
                })
                obs_count += 1
            except (ValueError, TypeError):
                pass
    print(f"✅ {obs_count} numeric vitals")
    
    cursor.close()
    conn.close()
    
    phase1_time = time.time() - phase1_start
    print(f"   ⏱️  Phase 1 completed in {phase1_time:.2f}s")
    
    # ========== PHASE 2: PARALLEL PROCESSING ==========
    print(f"\n⚡ Phase 2: Computing vitals statistics with {num_cores} cores...")
    phase2_start = time.time()
    
    def process_patient_vitals(patient_id):
        """Compute vital statistics for one patient"""
        patient = patients[patient_id]
        patient_obs = obs_by_patient_code.get(patient_id, {})
        
        result = {
            'synthea_id': patient_id,
            'name': f"{patient['first_name']} {patient['last_name']}",
            'vitals_found': {},
            'data': []
        }
        
        for vital_name, loinc_code in vital_codes.items():
            obs_list = patient_obs.get(loinc_code, [])
            if obs_list:
                values = [o['value'] for o in obs_list]
                dates = [o['date'] for o in obs_list if o['date']]
                
                min_val = min(values)
                max_val = max(values)
                avg_val = sum(values) / len(values)
                first_date = min(dates) if dates else None
                last_date = max(dates) if dates else None
                count = len(values)
                
                result['vitals_found'][vital_name] = count
                result['data'].append((
                    patient_id, vital_name, loinc_code,
                    min_val, max_val, avg_val,
                    first_date, last_date, count
                ))
        
        return result
    
    patient_ids = list(patients.keys())
    results = []
    
    print(f"\n{'#':<5} {'Patient Name':<30} {'BP Sys':<8} {'BP Dia':<8} {'HR':<8} {'Weight':<8} {'Glucose':<8}")
    print("-" * 90)
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_cores) as executor:
        future_to_id = {executor.submit(process_patient_vitals, pid): pid for pid in patient_ids}
        
        completed = 0
        for future in concurrent.futures.as_completed(future_to_id):
            completed += 1
            result = future.result()
            results.append(result)
            
            vitals = result['vitals_found']
            bp_s = str(vitals.get('bp_systolic', '-'))
            bp_d = str(vitals.get('bp_diastolic', '-'))
            hr = str(vitals.get('heart_rate', '-'))
            wt = str(vitals.get('weight', '-'))
            gl = str(vitals.get('glucose', '-'))
            
            print(f"{completed:<5} {result['name']:<30} {bp_s:<8} {bp_d:<8} {hr:<8} {wt:<8} {gl:<8}")
            
            if completed % 25 == 0:
                elapsed = time.time() - phase2_start
                rate = completed / elapsed if elapsed > 0 else 0
                print(f"   📊 Progress: {completed}/{len(patient_ids)} | {rate:.1f}/sec")
    
    phase2_time = time.time() - phase2_start
    print(f"\n   ⏱️  Phase 2 completed in {phase2_time:.2f}s")
    
    # ========== PHASE 3: BULK WRITE ==========
    print("\n💾 Phase 3: Bulk writing to database...")
    phase3_start = time.time()
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    insert_sql = """
        INSERT INTO Patient_Vitals_Summary (
            synthea_patient_id, vital_type, vital_code,
            min_value, max_value, avg_value,
            first_measurement_date, last_measurement_date, measurement_count
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            min_value = VALUES(min_value), max_value = VALUES(max_value),
            avg_value = VALUES(avg_value),
            first_measurement_date = VALUES(first_measurement_date),
            last_measurement_date = VALUES(last_measurement_date),
            measurement_count = VALUES(measurement_count)
    """
    
    all_data = []
    for r in results:
        all_data.extend(r['data'])
    
    if all_data:
        cursor.executemany(insert_sql, all_data)
        conn.commit()
    
    cursor.close()
    conn.close()
    
    phase3_time = time.time() - phase3_start
    print(f"   ⏱️  Phase 3 completed in {phase3_time:.2f}s")
    
    # ========== SUMMARY ==========
    total_time = time.time() - start_time
    total_vitals = defaultdict(int)
    for r in results:
        for vname, vcount in r['vitals_found'].items():
            total_vitals[vname] += vcount
    
    print("\n" + "=" * 60)
    print("✅ Vitals Summary Complete!")
    print(f"   Total patients: {len(results)}")
    print(f"   Total records written: {len(all_data)}")
    for vital_name, count in total_vitals.items():
        print(f"   {vital_name}: {count} measurements")
    print(f"   Total time: {total_time:.2f}s")
    print("=" * 60)


def get_load_statistics(synthea_dir):
    """Get statistics about what will be loaded"""
    stats = {}
    files = [
        ('patients.csv', 'Patients'),
        ('organizations.csv', 'Organizations'),
        ('providers.csv', 'Providers'),
        ('encounters.csv', 'Encounters'),
        ('conditions.csv', 'Conditions'),
        ('medications.csv', 'Medications'),
        ('allergies.csv', 'Allergies'),
        ('observations.csv', 'Observations'),
        ('procedures.csv', 'Procedures'),
        ('careplans.csv', 'Care Plans'),
        ('immunizations.csv', 'Immunizations'),
        ('devices.csv', 'Devices'),
        ('imaging_studies.csv', 'Imaging Studies'),
    ]
    
    for filename, label in files:
        filepath = os.path.join(synthea_dir, filename)
        if os.path.exists(filepath):
            records = read_csv_file(filepath)
            stats[label] = len(records)
        else:
            stats[label] = 0
    
    return stats


def main():
    parser = argparse.ArgumentParser(description='Load Synthea data into MariaDB')
    parser.add_argument('--synthea-dir', default=DEFAULT_SYNTHEA_DIR,
                        help='Directory containing Synthea CSV files')
    parser.add_argument('--clear', action='store_true',
                        help='Clear existing data before loading')
    parser.add_argument('--skip-ai-features', action='store_true',
                        help='Skip AI feature extraction')
    args = parser.parse_args()
    
    print("=" * 60)
    print("🏥 Synthea to MariaDB Loader (with AI Model Support)")
    print("=" * 60)
    print(f"\nSynthea directory: {args.synthea_dir}")
    
    # Check if directory exists
    if not os.path.exists(args.synthea_dir):
        print(f"❌ Error: Directory not found: {args.synthea_dir}")
        print("\nPlease run Synthea first to generate patient data:")
        print("  java -jar synthea-with-dependencies.jar -p 50 --exporter.csv.export=true")
        return
    
    # Show statistics
    print("\n📊 Data to be loaded:")
    stats = get_load_statistics(args.synthea_dir)
    for label, count in stats.items():
        print(f"   {label}: {count}")
    
    # Create tables
    print("\n📐 Creating database tables...")
    create_synthea_tables()
    
    # Clear if requested
    if args.clear:
        print("\n🗑️  Clearing existing data...")
        clear_synthea_tables()
    
    # Load data in order (respecting foreign key constraints)
    print("\n" + "=" * 60)
    print("📥 Loading Synthea Data into MariaDB")
    print("=" * 60)
    
    load_patients(args.synthea_dir)
    load_organizations(args.synthea_dir)
    load_providers(args.synthea_dir)
    load_encounters(args.synthea_dir)
    load_conditions(args.synthea_dir)
    load_medications(args.synthea_dir)
    load_allergies(args.synthea_dir)
    load_observations(args.synthea_dir)
    load_procedures(args.synthea_dir)
    load_careplans(args.synthea_dir)
    load_immunizations(args.synthea_dir)
    load_devices(args.synthea_dir)
    load_imaging_studies(args.synthea_dir)
    
    # Extract AI features
    if not args.skip_ai_features:
        extract_patient_ai_features()
        populate_vitals_summary()
    
    print("\n" + "=" * 60)
    print("✅ Synthea data loaded successfully!")
    print("=" * 60)
    print("\nAI Model Integration:")
    print("   • Patient_AI_Features table populated with ML model inputs")
    print("   • Patient_Vitals_Summary table contains aggregated vitals")
    print("\nNext step: Run synthea_to_neo4j.py to sync to Neo4j knowledge graph")


if __name__ == '__main__':
    main()
